# This script is built for finding the netcdf library automatically.

find_path(HDF5_Fortran_INCLUDE_DIR h5f.mod $ENV{INCLUDE_HDF5} )

find_library(HDF5HL_Fortran_LIBRARY NAMES hdf5_hl_fortran PATHS $ENV{LIBRARY_HDF5})
find_library(HDF5_HL_LIBRARY NAMES hdf5_hl PATHS $ENV{LIBRARY_HDF5})
find_library(HDF5_Fortran_LIBRARY NAMES hdf5_fortran PATHS $ENV{LIBRARY_HDF5})
find_library(HDF5_LIBRARY NAMES hdf5 PATHS $ENV{LIBRARY_HDF5})

# find_library(HDF5_F90cstub_LIBRARY NAMES hdf5_f90cstub PATHS $ENV{LIBRARY_HDF5})
# find_library(HDF5_Tools_LIBRARY NAMES hdf5_tools PATHS $ENV{LIBRARY_HDF5})
# find_library(HDF5_HL_F90CSTUB_LIBRARY NAMES hdf5_hl_f90cstub PATHS $ENV{LIBRARY_HDF5})
find_library(ZLIB_LIBRARY NAMES z PATHS $ENV{LIBRARY_Z})

if (HDF5_Fortran_INCLUDE_DIR AND HDF5HL_Fortran_LIBRARY AND HDF5_HL_LIBRARY 
AND HDF5_Fortran_LIBRARY AND HDF5_LIBRARY)
#AND HDF5_F90cstub_LIBRARY AND HDF5_Tools_LIBRARY AND HDF5_HL_F90CSTUB_LIBRARY)
    set(HDF5_FOUND TRUE)
endif (HDF5_Fortran_INCLUDE_DIR AND HDF5HL_Fortran_LIBRARY AND HDF5_HL_LIBRARY 
AND HDF5_Fortran_LIBRARY AND HDF5_LIBRARY)
#AND HDF5_F90cstub_LIBRARY AND HDF5_Tools_LIBRARY AND HDF5_HL_F90CSTUB_LIBRARY)
