# This script is built for finding the rttov library automatically.

find_path(RTTOV_INCLUDE_DIR rttov_read_coefs.interface $ENV{INCLUDE_RTTOV})
find_path(RTTOV_MOD_DIR rttov_types.mod $ENV{MOD_RTTOV})
find_library(RTTOV_LIBRARY NAMES librttov_main.a PATHS $ENV{LIBRARY_RTTOV})
find_library(RTTOV_COEF_IO_LIBRARY NAMES librttov_coef_io.a PATHS $ENV{LIBRARY_RTTOV})
find_library(RTTOV_EMIS_ATLAS_LIBRARY NAMES librttov_emis_atlas.a PATHS $ENV{LIBRARY_RTTOV})
find_library(RTTOV_HDF_LIBRARY NAMES librttov_hdf.a PATHS $ENV{LIBRARY_RTTOV})
find_library(RTTOV_OTHER_LIBRARY NAMES librttov_other.a PATHS $ENV{LIBRARY_RTTOV})
find_library(RTTOV_PARALLEL_LIBRARY NAMES librttov_parallel.a PATHS $ENV{LIBRARY_RTTOV})

if (RTTOV_INCLUDE_DIR AND RTTOV_LIBRARY AND RTTOV_PARALLEL_LIBRARY AND RTTOV_MOD_DIR AND RTTOV_OTHER_LIBRARY)
    set(RTTOV_FOUND TRUE)
endif (RTTOV_INCLUDE_DIR AND RTTOV_LIBRARY AND RTTOV_PARALLEL_LIBRARY AND RTTOV_MOD_DIR AND RTTOV_OTHER_LIBRARY)

MESSAGE(STATUS "RTTOV_LIBRARY: " ${RTTOV_LIBRARY})
