!  Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 31 May 2021 11:17
!
!  Differentiation of cumfwd in reverse (adjoint) mode:
!   gradient     of useful results: precip vwnd uwnd par_theta
!                par_q pres wwnd
!   with respect to varying inputs: precip vwnd uwnd par_theta
!                theta qvapor par_q pres wwnd
!
!!--------------------------------------------------------------------------------------------------
! PROJECT           : MOTOR-DA
! AFFILIATION       : Guangdong-HongKong-Macao Greater Bay Area Weather
! Research Center for Monitoring Warning and Forecasting (GBA-MWF)
!                     Shenzhen Institute of Meteorological Innovation
! AUTOHR(S)         : Jilong CHEN
! VERSION           : V 0.0
! HISTORY           :
!   Created by Jilong CHEN (jchen@link.cuhk.edu.hk), 2021/1/26, @GBA-MWF,
!   Shenzhen
!!--------------------------------------------------------------------------------------------------

!> @brief
!!

MODULE CumFwdB_m

  USE Interp1D2_m, ONLY: Interp1d
  USE Tendency2_m, ONLY: Tendency2
  USE divergence2_m, ONLY: divergence
  USE Interp1DB_m
  USE TendencyB_m
  USE divergenceB_m
  USE parameters_m, ONLY: g, cp, Lv, k_d, r_k_d, epsw_r, gamma_d, r_d, TK

CONTAINS
  SUBROUTINE CUMFWD_B(uwnd, uwndb, vwnd, vwndb, wwnd, wwndb, pres, presb, &
        & theta, thetab, qvapor, qvaporb, ztop, cell_dist, cell_stcl, gph, &
        & cell_type, sigma, topo, vlevel, vlevel1d, size_3m, num_cell, num_icell, par_theta&
        & , par_thetab, par_q, par_qb, precipb)
    IMPLICIT NONE
    INTEGER*4, INTENT(IN) :: vlevel, vlevel1d, size_3m, num_cell, num_icell, &
  & cell_stcl(:, :), cell_type(:)
    REAL*8, DIMENSION(9, num_cell), INTENT(IN) :: cell_dist
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(IN) :: uwnd, vwnd, wwnd, &
  & theta, qvapor, pres, gph
    REAL*8, DIMENSION(vlevel, num_cell) :: uwndb, vwndb, wwndb, thetab, &
  & qvaporb, presb
    REAL*8, DIMENSION(:), INTENT(IN) :: sigma, topo
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(INOUT) :: par_theta, par_q
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(INOUT) :: par_thetab, &
  & par_qb
    !   REAL*8, DIMENSION(:), INTENT(INOUT) :: precip
    REAL*8, DIMENSION(:), INTENT(INOUT) :: precipb
    REAL*8, INTENT(IN) :: ztop
    INTEGER*4 :: i, k, k_ref, k_bot, i_e, i_w, i_n, i_s, keps, kgph, &
  & vlevel1d2
    ! REAL(8), DIMENSION(:, :), ALLOCATABLE :: rhod, qu, qv, qw, temp
    REAL*8 :: rhod(vlevel, num_cell), qu(vlevel, num_cell), qv(vlevel, &
  & num_cell), qw(vlevel, num_cell), temp(vlevel, num_cell), uwnd1d(&
  & vlevel1d), vwnd1d(vlevel1d), wwnd1d(vlevel1d), theta1d(vlevel1d), &
  & temp1d(vlevel1d), qvapor1d(vlevel1d), pres1d(vlevel1d), gph1d(vlevel1d&
  & ), c_theta(vlevel), c_q(vlevel), tlcl(vlevel1d), beta_theta(vlevel1d)&
  & , theta_e(vlevel1d), temp_c(vlevel1d), theta_c(vlevel1d), q_c(vlevel1d&
  & ), dtheta(vlevel1d), theta_down(vlevel1d), theta_con(vlevel1d), q_con(&
  & vlevel1d), q_cont(vlevel1d), gph1dm(vlevel1d - 1), pm(vlevel1d - 1), psat(&
  & vlevel1d), qsat(vlevel1d), act_ht(vlevel1d), dtheta_dz(vlevel1d - 1), &
  & dtheta_m(vlevel1d - 1), act_cin(vlevel1d), act_dth_cin(vlevel1d), z_u(&
  & vlevel1d), act_zu(vlevel1d), act_dth_cape(vlevel1d), z_u2(vlevel1d), &
  & act_zu2(vlevel1d), act_dth_d(vlevel1d), act_dth_m(vlevel1d), divq(&
  & vlevel), qu_c(vlevel), qu_e(vlevel), qu_w(vlevel), qv_c(vlevel), qv_s(&
  & vlevel), qv_n(vlevel), qw_c(vlevel), theta1d_e(vlevel), theta1d_w(&
  & vlevel), theta1d_n(vlevel), theta1d_s(vlevel), theta1d_c(vlevel), &
  & q1d_n(vlevel), q1d_s(vlevel), q1d_e(vlevel), q1d_w(vlevel), q1d_c(&
  & vlevel), uwnd1d_c(vlevel), vwnd1d_c(vlevel), wwnd1d_c(vlevel), &
  & d_theta_con(vlevel1d), act_ht_m(vlevel1d - 1), d_theta_con_m(vlevel1d - 1)&
  & , q_con_m(vlevel1d - 1), gph1dm2(size_3m), dtheta_m2(size_3m), &
  & dtheta_dz2(size_3m), pm2t(size_3m), pm2(size_3m), act_dthz_ct(size_3m)&
  & , act_dth_ct(size_3m), act_dthz_lfc(size_3m), act_dth_lfc(size_3m), &
  & act_p500_ct(size_3m), act_p500_lfc(size_3m)
    REAL*8 :: act_ct(size_3m), act_lfc(size_3m), dgphm(size_3m - 1), act_pt(&
  & size_3m), act_lfc2(size_3m), rhod1d(vlevel1d)
    REAL*8 :: rhodb(vlevel, num_cell), qub(vlevel, num_cell), qvb(vlevel, &
  & num_cell), qwb(vlevel, num_cell), tempb(vlevel, num_cell), theta1db(&
  & vlevel1d), temp1db(vlevel1d), qvapor1db(vlevel1d), pres1db(vlevel1d), &
  & c_thetab(vlevel), c_qb(vlevel), tlclb(vlevel1d), beta_thetab(vlevel1d)&
  & , theta_eb(vlevel1d), temp_cb(vlevel1d), theta_cb(vlevel1d), q_cb(&
  & vlevel1d), dthetab(vlevel1d), theta_downb(vlevel1d), theta_conb(&
  & vlevel1d), q_conb(vlevel1d), q_contb(vlevel1d), pmb(vlevel1d - 1), psatb&
  & (vlevel1d), qsatb(vlevel1d), act_htb(vlevel1d), dtheta_dzb(vlevel1d - 1)&
  & , dtheta_mb(vlevel1d - 1), act_cinb(vlevel1d), act_dth_cinb(vlevel1d), &
  & z_ub(vlevel1d), act_zub(vlevel1d), act_dth_capeb(vlevel1d), z_u2b(&
  & vlevel1d), act_zu2b(vlevel1d), act_dth_db(vlevel1d), act_dth_mb(&
  & vlevel1d), divqb(vlevel), qu_cb(vlevel), qu_eb(vlevel), qu_wb(vlevel)&
  & , qv_cb(vlevel), qv_sb(vlevel), qv_nb(vlevel), qw_cb(vlevel), &
  & theta1d_eb(vlevel), theta1d_wb(vlevel), theta1d_nb(vlevel), theta1d_sb&
  & (vlevel), theta1d_cb(vlevel), q1d_nb(vlevel), q1d_sb(vlevel), q1d_eb(&
  & vlevel), q1d_wb(vlevel), q1d_cb(vlevel), uwnd1d_cb(vlevel), vwnd1d_cb(&
  & vlevel), wwnd1d_cb(vlevel), d_theta_conb(vlevel1d), act_ht_mb(vlevel1d&
  & - 1), d_theta_con_mb(vlevel1d - 1), q_con_mb(vlevel1d - 1), dtheta_m2b(&
  & size_3m), dtheta_dz2b(size_3m), pm2tb(size_3m), pm2b(size_3m), &
  & act_dthz_ctb(size_3m), act_dth_ctb(size_3m), act_dthz_lfcb(size_3m), &
  & act_dth_lfcb(size_3m), act_p500_ctb(size_3m), act_p500_lfcb(size_3m), &
  & act_ctb(size_3m), act_lfcb(size_3m), act_ptb(size_3m), act_lfc2b(&
  & size_3m), rhod1db(vlevel1d)
    REAL*8 :: a, qvapor1dmean, pres1dmean, gph1dmean, temp1dmean, tb, tb1&
  & , hb, tempt1, tempt2, est1, est2, gamma_m1, gamma_m2, cape, cin, &
  & avg_dtheta, std_dtheta, max_dtheta, d, act_dz, act_dthetae, act_p500, &
  & lfct, htt, lfc, ht, pt, act_sum_ct, act_cape, tlcl1, fts, dfts, rh, &
  & act_rh, b_param, ir, act_ir, sum_act_zu2, sum_act_zu2_p2, dth_m, &
  & dth_std, q1d_sum, qsat_sum, c_star, d_c_star, d_3m
    REAL*8 :: qvapor1dmeanb, pres1dmeanb, temp1dmeanb, tbb, tb1b, hbb, &
  & tempt1b, tempt2b, est1b, est2b, gamma_m1b, gamma_m2b, capeb, cinb, &
  & max_dthetab, db, act_dzb, act_dthetaeb, act_p500b, lfctb, httb, lfcb, &
  & htb, ptb, act_sum_ctb, act_capeb, tlcl1b, ftsb, dftsb, rhb, act_rhb, &
  & b_paramb, irb, act_irb, sum_act_zu2b, sum_act_zu2_p2b, dth_mb, &
  & dth_stdb, q1d_sumb, qsat_sumb, c_starb, d_c_starb
    INTRINSIC DLOG
    INTRINSIC DEXP
    INTRINSIC TANH
    INTRINSIC SUM
    INTRINSIC DABS
    INTRINSIC MINLOC
    INTRINSIC EXP
    INTRINSIC SQRT
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: dabs0
    LOGICAL, DIMENSION(vlevel1d) :: mask
    REAL*8 :: result1
    REAL*8 :: result1b
    REAL*8 :: result2
    REAL*8 :: result2b
    REAL*8, DIMENSION(vlevel - 2) :: arg1
    REAL*8, DIMENSION(vlevel - 2) :: arg1b
    REAL*8, DIMENSION(vlevel, num_cell) :: temp0
    REAL*8, DIMENSION(vlevel, num_cell) :: tempb0
    DOUBLE PRECISION :: temp1
    DOUBLE PRECISION :: tempb1
    DOUBLE PRECISION :: temp2
    DOUBLE PRECISION :: tempb2
    REAL*8 :: temp3
    REAL*8 :: tempb3
    REAL*8, DIMENSION(vlevel1d) :: temp4
    REAL*8, DIMENSION(vlevel1d) :: tempb4
    REAL*8 :: temp5
    REAL*8 :: tempb5
    REAL*8 :: temp6
    REAL*8 :: temp7
    REAL*8 :: temp8
    REAL*8 :: temp9
    REAL*8 :: tempb6
    REAL*8 :: temp10
    REAL*8 :: temp11
    REAL*8 :: tempb7
    REAL*8 :: tempb8
    REAL*8 :: temp12
    REAL*8 :: tempb9
    REAL*8 :: tempb10
    REAL*8 :: tempb11
    REAL*8, DIMENSION(vlevel1d - 1) :: tempb12
    DOUBLE PRECISION, DIMENSION(size_3m) :: temp13
    REAL*8, DIMENSION(size_3m) :: temp14
    REAL*8, DIMENSION(size_3m - 1) :: tempb13
    REAL*8, DIMENSION(vlevel - 2) :: tempb14
    REAL*8, DIMENSION(vlevel1d) :: temp15
    REAL*8, DIMENSION(vlevel1d) :: tempb15
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: temp16
    INTEGER :: branch
    INTEGER :: ad_from
    ! vLevel1d = vLevel - 1
    vlevel1d2 = vlevel1d - 1

    a = 2.4304D02 - tk
    temp = theta * (pres / 1.0D05)**k_d
    rhod = pres / temp / r_d / (1 + qvapor)
    qu = rhod * qvapor * uwnd
    qv = rhod * qvapor * vwnd
    qw = rhod * qvapor * wwnd
    DO i = 1, num_icell
      IF (cell_type(i) .EQ. 0) THEN
        CALL PUSHREAL8ARRAY(pres1d, vlevel1d)
        pres1d = pres(2:vlevel, i) / 1.0D02
        CALL PUSHREAL8ARRAY(theta1d, vlevel1d)
        theta1d = theta(2:vlevel, i)
        CALL PUSHREAL8ARRAY(temp1d, vlevel1d)
        temp1d = temp(2:vlevel, i)
        CALL PUSHREAL8ARRAY(qvapor1d, vlevel1d)
        qvapor1d = qvapor(2:vlevel, i)
        CALL PUSHREAL8ARRAY(gph1d, vlevel1d)
        gph1d = gph(2:vlevel, i)
        CALL PUSHREAL8ARRAY(rhod1d, vlevel1d)
        rhod1d = rhod(2:vlevel, i)
        CALL PUSHREAL8ARRAY(gph1dm, vlevel1d - 1)
        gph1dm = (gph1d(2:vlevel1d) + gph1d(1:vlevel1d - 1)) / 2.0D0
        d_3m = (gph1dm(vlevel1d - 1) - gph1dm(1)) / size_3m
        DO kgph = 1, size_3m
          CALL PUSHREAL8(gph1dm2(kgph))
          gph1dm2(kgph) = gph1dm(1) + d_3m * (kgph - 1)
        END DO
        ! size_3m = floor((gph1dm(vLevel1d - 1) - gph1dm(1))/3.0D0)+1
        ! ALLOCATE (gph1dm2(size_3m), dtheta_m2(size_3m), dtheta_dz2(size_3m), &
        !           Pm2t(size_3m), Pm2(size_3m),act_dthz_ct(size_3m), &
        !           act_dth_ct(size_3m), act_dthz_lfc(size_3m), &
        !           act_dth_lfc(size_3m), &
        !            act_p500_ct(size_3m), &
        !           act_p500_lfc(size_3m), Act_ct(size_3m), Act_lfc(size_3m), &
        !           dgphm(size_3m - 1), Act_Pt(size_3m), Act_lfc2(size_3m))
        c_theta(1) = 0.0D0
        c_q(1) = 0.0D0
        CALL PUSHREAL8ARRAY(tlcl, vlevel1d)
        tlcl = temp1d
        DO k = 1, vlevel1d
          DO keps = 1, 5
            CALL PUSHREAL8(fts)
            fts = (tlcl(k) + a) / k_d * DLOG(tlcl(k)) + tlcl(k) * (DLOG(qvapor1d(k&
  &           )) + DLOG(pres1d(k)) - 1.0D0 / k_d * DLOG(temp1d(k)) - DLOG((epsw_r +&
  &           qvapor1d(k)) * 6.1094D0) - 17.625D0) + a * (DLOG(qvapor1d(k)) + DLOG&
  &           (pres1d(k)) - 1.0D0 / k_d * DLOG(temp1d(k)) - DLOG((epsw_r + qvapor1d(&
  &           k)) * 6.1094D0)) + 17.625D0 * tk
            CALL PUSHREAL8(dfts)
            dfts = DLOG(tlcl(k)) / k_d + (tlcl(k) + a) / k_d / tlcl(k) + (DLOG(&
  &           qvapor1d(k)) + DLOG(pres1d(k)) - 1.0D0 / k_d * DLOG(temp1d(k)) - DLOG(&
  &           (epsw_r + qvapor1d(k)) * 6.1094D0) - 17.625D0)
            tlcl1 = tlcl(k) - fts / dfts
            CALL PUSHREAL8(tlcl(k))
            tlcl(k) = tlcl1
          END DO
        END DO
        CALL PUSHREAL8ARRAY(theta_e, vlevel1d)
        theta_e = theta1d * DEXP(lv * qvapor1d / cp / tlcl)
        k_ref = vlevel / 2
        ! The first activation function
        CALL PUSHREAL8(act_dthetae)
        act_dthetae = (TANH((theta_e(1) - theta_e(k_ref) - 1.0D0) * 2.0D0) + 1.0D0&
  &       ) / 2.0D0
        CALL PUSHREAL8(qvapor1dmean)
        qvapor1dmean = SUM(qvapor1d(1:3)) / 3.0D0
        CALL PUSHREAL8(pres1dmean)
        pres1dmean = SUM(pres1d(1:3)) / 3.0D0
        CALL PUSHREAL8(temp1dmean)
        temp1dmean = SUM(temp1d(1:3)) / 3.0D0
        gph1dmean = SUM(gph1d(1:3)) / 3.0D0
        tb = temp1dmean
        DO keps = 1, 5
          CALL PUSHREAL8(fts)
          fts = (tb + a) * r_k_d * DLOG(tb) + tb * (DLOG(qvapor1dmean) + DLOG(&
  &         pres1dmean) - r_k_d * DLOG(temp1dmean) - DLOG((epsw_r + qvapor1dmean) *&
  &         6.1094D0) - 1.7625D01) + a * (DLOG(qvapor1dmean) + DLOG(pres1dmean) -&
  &         r_k_d * DLOG(temp1dmean) - DLOG((epsw_r + qvapor1dmean) * 6.1094D0)) +&
  &         1.7625D01 * tk
          CALL PUSHREAL8(dfts)
          dfts = DLOG(tb) * r_k_d + (tb + a) * r_k_d / tb + (DLOG(qvapor1dmean) +&
  &         DLOG(pres1dmean) - r_k_d * DLOG(temp1dmean) - DLOG((epsw_r +&
  &         qvapor1dmean) * 6.1094D0) - 1.7625D01)
          tb1 = tb - fts / dfts
          CALL PUSHREAL8(tb)
          tb = tb1
        END DO
        CALL PUSHREAL8(hb)
        hb = (temp1dmean - tb) / g * cp + gph1dmean
        CALL PUSHBOOLEANARRAY(mask, vlevel1d)
        mask = gph1d - hb .GE. 0.
        WHERE (mask)
          dabs0 = gph1d - hb
        ELSEWHERE
          dabs0 = -(gph1d - hb)
        END WHERE
        ! Cloud base found
        k_bot = MINLOC(dabs0, 1)
        q_c = qvapor1d
        CALL PUSHREAL8ARRAY(theta_c(1:k_bot), k_bot)
        theta_c(1:k_bot) = theta1d(1)
        CALL PUSHREAL8(temp_c(k_bot))
        temp_c(k_bot) = tb
        ad_from = k_bot
        DO k = ad_from, vlevel1d - 1
          CALL PUSHREAL8(tempt1)
          tempt1 = temp_c(k)
          IF (tempt1 .LE. 3.011D01) THEN
            q_c(k) = 0.0D0
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHREAL8(est1)
            est1 = 6.1094D0 * EXP(1.7625D01 * (tempt1 - tk) / (tempt1 - 3.011D01))
            q_c(k) = est1 / (pres1d(k) - est1) * epsw_r
            gamma_m1 = -(gamma_d * ((1.0D0 + lv * est1 * epsw_r / pres1d(k) / r_d /&
  &           tempt1) / (1.0D0 + lv**2.0D0 * epsw_r**2.0D0 * est1 / cp / pres1d(k) / r_d&
  &           / tempt1**2.0D0)))
            CALL PUSHREAL8(tempt2)
            tempt2 = tempt1 + gamma_m1 * (gph1d(k + 1) - gph1d(k))
            IF (tempt2 .GT. 3.011D01) THEN
              CALL PUSHREAL8(est2)
              est2 = 6.1094D0 * EXP(1.7625D01 * (tempt2 - tk) / (tempt2 - 3.011D01))
              gamma_m2 = -(gamma_d * ((1.0D0 + lv * est2 * epsw_r / pres1d(k + 1) / r_d /&
  &             tempt2) / (1.0D0 + lv**2.0D0 * epsw_r**2.0D0 * est2 / cp / pres1d(k + 1)&
  &             / r_d / tempt2**2.0D0)))
              CALL PUSHCONTROL1B(0)
            ELSE
              gamma_m2 = -gamma_d
              CALL PUSHCONTROL1B(1)
            END IF
            CALL PUSHREAL8(temp_c(k + 1))
            temp_c(k + 1) = tempt1 + (gamma_m1 + gamma_m2) * (gph1d(k + 1) - gph1d(k&
  &           )) / 2.0D0
            CALL PUSHREAL8(theta_c(k + 1))
            theta_c(k + 1) = temp_c(k + 1) * (1.0D03 / pres1d(k + 1))**k_d
            CALL PUSHCONTROL1B(0)
          END IF
        END DO
        CALL PUSHINTEGER4(ad_from)
        CALL PUSHREAL8ARRAY(dtheta, vlevel1d)
        dtheta = theta_c - theta1d
        CALL PUSHREAL8ARRAY(dtheta_dz, vlevel1d - 1)
        dtheta_dz = (dtheta(2:vlevel1d) - dtheta(1:vlevel1d - 1)) / (gph1d(2:&
  &       vlevel1d) - gph1d(1:vlevel1d - 1))
        CALL PUSHREAL8ARRAY(dtheta_m, vlevel1d - 1)
        dtheta_m = (dtheta(2:vlevel1d) + dtheta(1:vlevel1d - 1)) / 2.0D0
        CALL PUSHREAL8ARRAY(pm, vlevel1d - 1)
        pm = (DLOG(pres1d(2:vlevel1d)) + DLOG(pres1d(1:vlevel1d - 1))) / 2.0D0
        ! DO kgph = 1, size_3m
        !     gph1dm2(kgph) = gph1dm(1) + 3.0D0*(kgph-1)
        ! END DO
        CALL PUSHREAL8ARRAY(dtheta_m2, size_3m)
        CALL INTERP1D(gph1dm, dtheta_m, vlevel1d2, gph1dm2, dtheta_m2)
        CALL PUSHREAL8ARRAY(dtheta_dz2, size_3m)
        CALL INTERP1D(gph1dm, dtheta_dz, vlevel1d2, gph1dm2, dtheta_dz2)
        CALL PUSHREAL8ARRAY(pm2t, size_3m)
        CALL INTERP1D(gph1dm, pm, vlevel1d2, gph1dm2, pm2t)
        CALL PUSHREAL8ARRAY(pm2, size_3m)
        pm2 = EXP(pm2t)
        CALL PUSHREAL8ARRAY(act_p500_ct, size_3m)
        act_p500_ct = (TANH((5.0D02 - pm2) / 8.0D01) + 1.0D0) / 2.0D0
        CALL PUSHREAL8ARRAY(act_p500_lfc, size_3m)
        act_p500_lfc = (TANH((-5.0D02 + pm2) / 8.0D01) + 1.0D0) / 2.0D0
        CALL PUSHREAL8ARRAY(act_dthz_ct, size_3m)
        act_dthz_ct = (-TANH(dtheta_dz2 * 3.0D04) + 1.0D0) / 2.0D0
        act_dth_ct = 1.0D0 / (1.0D0 + 5.0D03 * dtheta_m2**4.0D0)
        CALL PUSHREAL8ARRAY(act_dthz_lfc, size_3m)
        act_dthz_lfc = (TANH(dtheta_dz2 * 1.0D04) + 1.0D0) / 2.0D0
        CALL PUSHREAL8ARRAY(act_dth_lfc, size_3m)
        act_dth_lfc = 1.0D0 / (1.0D0 + 5.0D03 * dtheta_m2**4.0D0)
        act_ct = act_p500_ct * act_dthz_ct * act_dth_ct
        CALL PUSHREAL8(act_sum_ct)
        act_sum_ct = 1.0D0 / (1.0D0 + EXP(-(1.0D01 * SUM(act_ct)))) * 2.0D0 - &
  &       1.0D0
        act_lfc = act_p500_lfc * act_dthz_lfc * act_dth_lfc
        dgphm = gph1dm2(2:size_3m) - gph1dm2(1:size_3m - 1)
        CALL PUSHREAL8(result1)
        result1 = SUM((act_ct(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_ct(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(result2)
        result2 = SUM((act_ct(1:size_3m - 1) + act_ct(2:size_3m)) * dgphm)
        CALL PUSHREAL8(htt)
        htt = act_sum_ct * result1 / result2
        CALL PUSHREAL8(result1)
        result1 = SUM((act_lfc(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_lfc(2&
  &       :size_3m) * gph1dm2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(result2)
        result2 = SUM((act_lfc(1:size_3m - 1) + act_lfc(2:size_3m)) * dgphm)
        CALL PUSHREAL8(lfct)
        lfct = act_sum_ct * result1 / result2
        act_pt = 1.0D0 / (1.0D0 + (gph1dm2 - htt)**4.0D0 / 1.0D08)
        act_lfc2 = 1.0D0 / (1.0D0 + (gph1dm2 - lfct)**4.0D0 / 1.0D08)
        CALL PUSHREAL8(result1)
        result1 = SUM((act_pt(1:size_3m - 1) * pm2(1:size_3m - 1) + act_pt(2:&
  &       size_3m) * pm2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(result2)
        result2 = SUM((act_pt(1:size_3m - 1) + act_pt(2:size_3m)) * dgphm)
        CALL PUSHREAL8(pt)
        pt = result1 / result2
        CALL PUSHREAL8(result1)
        result1 = SUM((act_pt(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_pt(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(result2)
        result2 = SUM((act_pt(1:size_3m - 1) + act_pt(2:size_3m)) * dgphm)
        CALL PUSHREAL8(ht)
        ht = result1 / result2
        CALL PUSHREAL8(result1)
        result1 = SUM((act_lfc2(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_lfc2&
  &       (2:size_3m) * gph1dm2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(result2)
        result2 = SUM((act_lfc2(1:size_3m - 1) + act_lfc2(2:size_3m)) * dgphm)
        CALL PUSHREAL8(lfc)
        lfc = result1 / result2
        CALL PUSHREAL8(act_dz)
        act_dz = (TANH((ht - lfc - 3.0D03) / 5.0D02) + 1.0D0) / 2.0D0
        ! Third activation function
        CALL PUSHREAL8(act_p500)
        act_p500 = (TANH((5.0D02 - pt) / 5.0D01) + 1.0D0) / 2.0D0
        CALL PUSHREAL8ARRAY(act_cin, vlevel1d)
        act_cin = (TANH((lfc - gph1d) / 5.0D02) + 1.0D0) / 2.0D0
        act_dth_cin = act_cin * dtheta
        CALL PUSHREAL8(result1)
        result1 = SUM((act_dth_cin(2:vlevel1d) + act_dth_cin(1:vlevel1d - 1)) *&
  &       (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)))
        CALL PUSHREAL8(cin)
        cin = result1 / 2.0D0
        CALL PUSHREAL8ARRAY(z_u, vlevel1d)
        z_u = (2.0D0 * gph1d - ht - lfc) / (ht - lfc)
        CALL PUSHREAL8ARRAY(act_zu, vlevel1d)
        act_zu = 1.0D0 / (1.0D0 + z_u**8.0D0)
        act_dth_cape = act_zu * dtheta
        result1 = SUM((act_dth_cape(2:vlevel1d) + act_dth_cape(1:vlevel1d - 1)&
  &       ) * (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)))
        CALL PUSHREAL8(cape)
        cape = result1 / 2.0D0
        ! Fourth activation function
        CALL PUSHREAL8(act_cape)
        act_cape = (TANH((cape + 1.0D0 * cin) / 1.0D03 - 2.5D0) + 1.0D0) / 2.0D0
        z_u2 = (2.0D0 * gph1d - ht - hb) / (ht - hb)
        act_zu2 = 1.0D0 / (1.0D0 + z_u2**8.0D0)
        CALL PUSHREAL8(sum_act_zu2)
        sum_act_zu2 = SUM(act_zu2)
        CALL PUSHREAL8(sum_act_zu2_p2)
        sum_act_zu2_p2 = SUM(act_zu2**2.0D0)
        act_dth_d = act_zu2 * dtheta
        CALL PUSHREAL8(dth_m)
        dth_m = SUM(act_dth_d) / sum_act_zu2
        act_dth_m = dth_m * act_zu2
        dth_std = SQRT(SUM((act_dth_d - act_dth_m)**2.0D0) / sum_act_zu2_p2)
        CALL PUSHREAL8(max_dtheta)
        max_dtheta = dth_m + 1.5D0 * dth_std
        CALL PUSHREAL8(d)
        d = 1.0D0 / (1.0D0 + EXP(-max_dtheta + 2.5D0)) * 5.0D0
        CALL PUSHREAL8ARRAY(theta_down, vlevel1d)
        theta_down = -(EXP(-(4.0D0 * SQRT(gph1d - gph1d(1)) / SQRT(ht))) * d) + &
  &       theta1d
        CALL PUSHREAL8ARRAY(beta_theta, vlevel1d)
        beta_theta = EXP(-(5.0D0 * SQRT(gph1d - gph1d(1)) / SQRT(ht)))
        theta_con = beta_theta * theta_down + (1.0D0 - beta_theta) * theta_c
        CALL PUSHREAL8ARRAY(q_cont, vlevel1d)
        q_cont = q_c - qvapor1d
        q_con = q_cont * act_zu2
        CALL PUSHINTEGER4(i_e)
        i_e = cell_stcl(6, i)
        CALL PUSHINTEGER4(i_w)
        i_w = cell_stcl(4, i)
        CALL PUSHINTEGER4(i_n)
        i_n = cell_stcl(8, i)
        CALL PUSHINTEGER4(i_s)
        i_s = cell_stcl(2, i)
        qu_c = qu(:, i)
        qu_e = qu(:, i_e)
        qu_w = qu(:, i_w)
        qv_c = qv(:, i)
        qv_n = qv(:, i_n)
        qv_s = qv(:, i_s)
        qw_c = qw(:, i)
        CALL PUSHREAL8ARRAY(divq, vlevel)
        CALL PUSHINTEGER4(vlevel)
        CALL DIVERGENCE(qu_c, qu_w, qu_e, qv_c, qv_s, qv_n, qw_c, sigma, &
  &               ztop, topo(i), topo(i_w), topo(i_e), topo(i_s), topo(i_n&
  &               ), cell_dist(4, i), cell_dist(2, i), vlevel, divq)
        CALL PUSHREAL8ARRAY(act_ht, vlevel1d)
        act_ht = (TANH((-gph1d + ht) / 1.0D02) + 1.0D0) / 2.0D0
        arg1(:) = (divq(2:vlevel - 1) * act_ht(1:vlevel1d - 1) + divq(3:vlevel) *&
  &       act_ht(2:vlevel1d)) * (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1))
        CALL PUSHREAL8(ir)
        ir = -(SUM(arg1(:)) / 2.0D0)
        CALL PUSHREAL8ARRAY(psat, vlevel1d)
        psat = 6.1094D0 * EXP(1.7625D01 * (temp1d - tk) / (temp1d - 3.011D01))
        qsat = psat / (pres1d - psat) * epsw_r
        CALL PUSHREAL8(q1d_sum)
        q1d_sum = SUM(qvapor1d * act_ht)
        CALL PUSHREAL8(qsat_sum)
        qsat_sum = SUM(qsat * act_ht)
        rh = q1d_sum / qsat_sum
        CALL PUSHREAL8(act_rh)
        act_rh = (TANH((rh - 6.8D-1) * 4.0D01) + 1.0D0) / 2.0D0
        b_param = act_rh * (1.0D0 - rh) * 5.0D-1 + (1.0D0 - act_rh)
        act_ht_m = (act_ht(2:vlevel1d) + act_ht(1:vlevel1d - 1)) / 2.0D0
        d_theta_con = theta_con - theta1d
        d_theta_con_m = (d_theta_con(2:vlevel1d) + d_theta_con(1:vlevel1d - 1)&
  &       ) / 2.0D0
        q_con_m = (q_con(2:vlevel1d) + q_con(1:vlevel1d - 1)) / 2.0D0
        CALL PUSHREAL8(act_ir)
        act_ir = (TANH((ir * 1.0D06 - 1.5D0) * 2.0D0) + 1.0D0) / 2.0D0
        c_star = act_ir * act_dthetae * act_dz * act_p500 * act_cape * ir
        d_c_star = b_param * c_star
        result1 = SUM(act_ht_m * d_theta_con_m * (gph1d(2:vlevel1d) - gph1d(1:&
  &       vlevel1d - 1)))
        c_theta(2:vlevel) = (c_star - d_c_star) / result1 * act_ht * d_theta_con *&
  &       lv / cp * (1.0D03 / pres1d)**k_d
        CALL PUSHREAL8(result1)
        result1 = SUM(act_ht_m * q_con_m * (gph1d(2:vlevel1d) - gph1d(1:vlevel1d&
  &       - 1)))
        c_q(2:vlevel) = d_c_star / result1 * act_ht * q_con / rhod1d
        ! precip(i) = act_Ir*act_dthetae*act_dz*act_P500*act_cape*(1.0D0 - b_param)*Ir*cu_dt
        theta1d_e = theta(:, i_e)
        theta1d_w = theta(:, i_w)
        theta1d_n = theta(:, i_n)
        theta1d_s = theta(:, i_s)
        theta1d_c = theta(:, i)
        uwnd1d_c = uwnd(:, i)
        vwnd1d_c = vwnd(:, i)
        wwnd1d_c = wwnd(:, i)
        CALL PUSHINTEGER4(vlevel)
        CALL TENDENCY2(uwnd1d_c, vwnd1d_c, wwnd1d_c, theta1d_c, theta1d_w, &
  &             theta1d_e, theta1d_s, theta1d_n, vlevel, sigma, ztop, topo&
  &             (i), topo(i_w), topo(i_e), topo(i_s), topo(i_n), cell_dist&
  &             (4, i), cell_dist(2, i), c_theta, par_theta(:, i))
        q1d_e = qvapor(:, i_e)
        q1d_w = qvapor(:, i_w)
        q1d_n = qvapor(:, i_n)
        q1d_s = qvapor(:, i_s)
        q1d_c = qvapor(:, i)
        CALL TENDENCY2(uwnd1d_c, vwnd1d_c, wwnd1d_c, q1d_c, q1d_w, q1d_e, &
  &             q1d_s, q1d_n, vlevel, sigma, ztop, topo(i), topo(i_w), &
  &             topo(i_e), topo(i_s), topo(i_n), cell_dist(4, i), &
  &             cell_dist(2, i), c_q, par_q(:, i))
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    thetab = 0.0_8
    qvaporb = 0.0_8
    c_thetab = 0.0_8
    pm2tb = 0.0_8
    tempb = 0.0_8
    qub = 0.0_8
    qvb = 0.0_8
    qwb = 0.0_8
    dtheta_m2b = 0.0_8
    temp_cb = 0.0_8
    theta_cb = 0.0_8
    rhodb = 0.0_8
    divqb = 0.0_8
    dtheta_dz2b = 0.0_8
    c_qb = 0.0_8
    DO i = num_icell, 1, -1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        temp4 = SQRT(gph1d - gph1d(1))
        temp12 = SQRT(ht)
        wwnd1d_c = wwnd(:, i)
        uwnd1d_c = uwnd(:, i)
        vwnd1d_c = vwnd(:, i)
        q1d_c = qvapor(:, i)
        q1d_e = qvapor(:, i_e)
        q1d_n = qvapor(:, i_n)
        q1d_s = qvapor(:, i_s)
        q1d_w = qvapor(:, i_w)
        uwnd1d_cb = 0.0_8
        vwnd1d_cb = 0.0_8
        wwnd1d_cb = 0.0_8
        CALL TENDENCY_B(uwnd1d_c, uwnd1d_cb, vwnd1d_c, vwnd1d_cb, wwnd1d_c&
  &               , wwnd1d_cb, q1d_c, q1d_cb, q1d_w, q1d_wb, q1d_e, q1d_eb&
  &               , q1d_s, q1d_sb, q1d_n, q1d_nb, vlevel, sigma, ztop, &
  &               topo(i), topo(i_w), topo(i_e), topo(i_s), topo(i_n), &
  &               cell_dist(4, i), cell_dist(2, i), c_q, c_qb, par_q(:, i)&
  &               , par_qb(:, i))
        qvaporb(:, i) = qvaporb(:, i) + q1d_cb
        qvaporb(:, i_s) = qvaporb(:, i_s) + q1d_sb
        qvaporb(:, i_n) = qvaporb(:, i_n) + q1d_nb
        qvaporb(:, i_w) = qvaporb(:, i_w) + q1d_wb
        qvaporb(:, i_e) = qvaporb(:, i_e) + q1d_eb
        theta1d_c = theta(:, i)
        theta1d_e = theta(:, i_e)
        theta1d_n = theta(:, i_n)
        theta1d_s = theta(:, i_s)
        theta1d_w = theta(:, i_w)
        CALL POPINTEGER4(vlevel)
        CALL TENDENCY_B(uwnd1d_c, uwnd1d_cb, vwnd1d_c, vwnd1d_cb, wwnd1d_c&
  &               , wwnd1d_cb, theta1d_c, theta1d_cb, theta1d_w, &
  &               theta1d_wb, theta1d_e, theta1d_eb, theta1d_s, theta1d_sb&
  &               , theta1d_n, theta1d_nb, vlevel, sigma, ztop, topo(i), &
  &               topo(i_w), topo(i_e), topo(i_s), topo(i_n), cell_dist(4&
  &               , i), cell_dist(2, i), c_theta, c_thetab, par_theta(:, i&
  &               ), par_thetab(:, i))
        wwndb(:, i) = wwndb(:, i) + wwnd1d_cb
        vwndb(:, i) = vwndb(:, i) + vwnd1d_cb
        uwndb(:, i) = uwndb(:, i) + uwnd1d_cb
        thetab(:, i) = thetab(:, i) + theta1d_cb
        thetab(:, i_s) = thetab(:, i_s) + theta1d_sb
        thetab(:, i_n) = thetab(:, i_n) + theta1d_nb
        thetab(:, i_w) = thetab(:, i_w) + theta1d_wb
        thetab(:, i_e) = thetab(:, i_e) + theta1d_eb
        z_u2 = (2.0D0 * gph1d - ht - hb) / (ht - hb)
        act_zu2 = 1.0D0 / (1.0D0 + z_u2**8.0D0)
        q_con = q_cont * act_zu2
        c_star = act_ir * act_dthetae * act_dz * act_p500 * act_cape * ir
        rh = q1d_sum / qsat_sum
        b_param = act_rh * (1.0D0 - rh) * 5.0D-1 + (1.0D0 - act_rh)
        d_c_star = b_param * c_star
        q_conb = 0.0_8
        act_htb = 0.0_8
        rhod1db = 0.0_8
        tempb15 = c_qb(2:vlevel) / (result1 * rhod1d)
        c_qb(2:vlevel) = 0.0_8
        d_c_starb = SUM(act_ht * q_con * tempb15)
        act_htb = d_c_star * q_con * tempb15
        q_conb = d_c_star * act_ht * tempb15
        tempb4 = -(d_c_star * act_ht * q_con * tempb15 / (result1 * rhod1d))
        result1b = SUM(rhod1d * tempb4)
        rhod1db = result1 * tempb4
        q_con_m = (q_con(2:vlevel1d) + q_con(1:vlevel1d - 1)) / 2.0D0
        act_ht_m = (act_ht(2:vlevel1d) + act_ht(1:vlevel1d - 1)) / 2.0D0
        q_con_mb = 0.0_8
        act_ht_mb = 0.0_8
        CALL POPREAL8(result1)
        tempb12 = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * result1b
        act_ht_mb = q_con_m * tempb12
        q_con_mb = act_ht_m * tempb12
        theta_con = beta_theta * theta_down + (1.0D0 - beta_theta) * theta_c
        d_theta_con = theta_con - theta1d
        d_theta_conb = 0.0_8
        pres1db = 0.0_8
        temp16 = 1.0D03 / pres1d
        temp15 = (c_star - d_c_star) * act_ht * d_theta_con / (cp * result1)
        tempb15 = temp16**k_d * lv * c_thetab(2:vlevel) / (cp * result1)
        tempb9 = SUM(act_ht * d_theta_con * tempb15)
        act_htb = act_htb + d_theta_con * (c_star - d_c_star) * tempb15
        d_theta_conb = act_ht * (c_star - d_c_star) * tempb15
        result1b = -(cp * SUM(temp15 * tempb15))
        d_c_starb = d_c_starb - tempb9 - precipb(i)
        c_starb = tempb9 + precipb(i) + b_param * d_c_starb
        d_theta_con_m = (d_theta_con(2:vlevel1d) + d_theta_con(1:vlevel1d - 1)&
  &       ) / 2.0D0
        d_theta_con_mb = 0.0_8
        tempb12 = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * result1b
        act_ht_mb = act_ht_mb + d_theta_con_m * tempb12
        d_theta_con_mb = act_ht_m * tempb12
        precipb(i) = 0.0_8
        b_paramb = c_star * d_c_starb
        temp11 = act_dz * act_p500
        tempb9 = act_cape * ir * c_starb
        tempb8 = act_ir * act_dthetae * temp11 * c_starb
        act_capeb = ir * tempb8
        act_irb = act_dthetae * temp11 * tempb9
        irb = act_cape * tempb8 + 1.0D06 * (1.0 - TANH(2.0D0 * (1.0D06 * ir - 1.5D0))&
                                           &       **2) * act_irb
        act_dthetaeb = act_ir * temp11 * tempb9
        tempb7 = act_ir * act_dthetae * tempb9
        act_dzb = act_p500 * tempb7
        act_p500b = act_dz * tempb7
        CALL POPREAL8(act_ir)
        q_conb(2:vlevel1d) = q_conb(2:vlevel1d) + q_con_mb / 2.0D0
        q_conb(1:vlevel1d - 1) = q_conb(1:vlevel1d - 1) + q_con_mb / 2.0D0
        d_theta_conb(2:vlevel1d) = d_theta_conb(2:vlevel1d) + &
  &       d_theta_con_mb / 2.0D0
        d_theta_conb(1:vlevel1d - 1) = d_theta_conb(1:vlevel1d - 1) + &
  &       d_theta_con_mb / 2.0D0
        theta1db = 0.0_8
        theta_conb = 0.0_8
        theta_conb = d_theta_conb
        act_htb(2:vlevel1d) = act_htb(2:vlevel1d) + act_ht_mb / 2.0D0
        act_htb(1:vlevel1d - 1) = act_htb(1:vlevel1d - 1) + act_ht_mb / 2.0D0
        act_rhb = ((1.0D0 - rh) * 5.0D-1 - 1.0) * b_paramb
        rhb = 4.0D01 * (1.0 - TANH(4.0D01 * (rh - 6.8D-1))**2) * act_rhb / 2.0D0 - &
  &       act_rh * 5.0D-1 * b_paramb
        CALL POPREAL8(act_rh)
        q1d_sumb = rhb / qsat_sum
        qsat_sumb = -(q1d_sum * rhb / qsat_sum**2)
        qsat = psat / (pres1d - psat) * epsw_r
        qsatb = 0.0_8
        CALL POPREAL8(qsat_sum)
        qsatb = act_ht * qsat_sumb
        act_htb = act_htb + qsat * qsat_sumb + qvapor1d * q1d_sumb
        qvapor1db = 0.0_8
        CALL POPREAL8(q1d_sum)
        psatb = 0.0_8
        tempb4 = epsw_r * qsatb / (pres1d - psat)
        tempb15 = -(psat * tempb4 / (pres1d - psat))
        WHERE (temp16 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT(k_d))&
  &     )
          pres1db = tempb15
        ELSEWHERE
          pres1db = tempb15 - temp16 * k_d * temp16**(k_d - 1) * temp15 * lv *&
  &         c_thetab(2:vlevel) / pres1d
        END WHERE
        c_thetab(2:vlevel) = 0.0_8
        psatb = tempb4 - tempb15
        temp1db = 0.0_8
        CALL POPREAL8ARRAY(psat, vlevel1d)
        tempb4 = 1.7625D01 * EXP(1.7625D01 * ((temp1d - tk) / (temp1d - 3.011D01))) *&
  &       6.1094D0 * psatb / (temp1d - 3.011D01)
        temp1db = (1.0 - (temp1d - tk) / (temp1d - 3.011D01)) * tempb4
        arg1b = 0.0_8
        CALL POPREAL8(ir)
        arg1b(:) = -(irb / 2.0D0)
        tempb14 = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * arg1b(:)
        divqb(2:vlevel - 1) = divqb(2:vlevel - 1) + act_ht(1:vlevel1d - 1) *&
  &       tempb14
        act_htb(1:vlevel1d - 1) = act_htb(1:vlevel1d - 1) + divq(2:vlevel - 1) *&
  &       tempb14
        divqb(3:vlevel) = divqb(3:vlevel) + act_ht(2:vlevel1d) * tempb14
        act_htb(2:vlevel1d) = act_htb(2:vlevel1d) + divq(3:vlevel) * tempb14
        q_contb = 0.0_8
        act_zu2b = 0.0_8
        q_contb = act_zu2 * q_conb
        qvapor1db = act_ht * q1d_sumb - q_contb
        CALL POPREAL8ARRAY(act_ht, vlevel1d)
        CALL POPINTEGER4(vlevel)
        CALL POPREAL8ARRAY(divq, vlevel)
        CALL DIVERGENCE_B(qu_c, qu_cb, qu_w, qu_wb, qu_e, qu_eb, qv_c, &
  &                 qv_cb, qv_s, qv_sb, qv_n, qv_nb, qw_c, qw_cb, sigma, &
  &                 ztop, topo(i), topo(i_w), topo(i_e), topo(i_s), topo(&
  &                 i_n), cell_dist(4, i), cell_dist(2, i), vlevel, divq, &
  &                 divqb)
        qwb(:, i) = qwb(:, i) + qw_cb
        qvb(:, i_s) = qvb(:, i_s) + qv_sb
        qvb(:, i_n) = qvb(:, i_n) + qv_nb
        qvb(:, i) = qvb(:, i) + qv_cb
        qub(:, i_w) = qub(:, i_w) + qu_wb
        qub(:, i_e) = qub(:, i_e) + qu_eb
        qub(:, i) = qub(:, i) + qu_cb
        CALL POPINTEGER4(i_s)
        CALL POPINTEGER4(i_n)
        CALL POPINTEGER4(i_w)
        CALL POPINTEGER4(i_e)
        q_cb = 0.0_8
        q_cb = q_contb
        beta_thetab = 0.0_8
        theta_downb = 0.0_8
        beta_thetab = (theta_down - theta_c) * theta_conb
        IF (ht .EQ. 0.0) THEN
          htb = SUM((1.0 - TANH((ht - gph1d) / 1.0D02)**2) * act_htb) / (1.0D02 *&
  &         2.0D0)
        ELSE
          htb = SUM((1.0 - TANH((ht - gph1d) / 1.0D02)**2) * act_htb) / (1.0D02 *&
  &         2.0D0) + 5.0D0 * SUM(temp4 * EXP(-(temp4 * (5.0D0 / temp12))) *&
  &         beta_thetab) / (2.0 * temp12**3)
        END IF
        theta_downb = beta_theta * theta_conb
        theta_cb = theta_cb + (1.0D0 - beta_theta) * theta_conb
        temp12 = SQRT(ht)
        temp2 = 4.0D0 / temp12
        temp4 = SQRT(gph1d - gph1d(1))
        IF (.NOT. ht .EQ. 0.0) htb = htb - temp2 * SUM(temp4 * EXP(-(temp4 *&
  &         temp2)) * theta_downb) * d / (2.0 * temp12**2)
        db = -SUM(EXP(-(temp4 * temp2)) * theta_downb)
        temp12 = EXP(-max_dtheta + 2.5D0) + 1.0D0
        max_dthetab = EXP(2.5D0 - max_dtheta) * 5.0D0 * db / temp12**2
        dth_stdb = 1.5D0 * max_dthetab
        act_dth_d = act_zu2 * dtheta
        act_dth_m = dth_m * act_zu2
        act_dth_db = 0.0_8
        act_dth_mb = 0.0_8
        temp12 = SUM((act_dth_d - act_dth_m)**2.0D0) / sum_act_zu2_p2
        IF (temp12 .EQ. 0.0) THEN
          tempb9 = 0.0_8
        ELSE
          tempb9 = dth_stdb / (sum_act_zu2_p2 * 2.0 * SQRT(temp12))
        END IF
        tempb4 = 2.0D0 * (act_dth_d - act_dth_m) * tempb9
        sum_act_zu2_p2b = -(temp12 * tempb9)
        act_dth_mb = -tempb4
        dth_mb = max_dthetab + SUM(act_zu2 * act_dth_mb)
        act_dth_db = tempb4 + dth_mb / sum_act_zu2
        sum_act_zu2b = -(SUM(act_dth_d) * dth_mb / sum_act_zu2**2)
        act_zu2b = q_cont * q_conb + dth_m * act_dth_mb + dtheta * act_dth_db + &
  &       2.0D0 * act_zu2 * sum_act_zu2_p2b + sum_act_zu2b
        CALL POPREAL8ARRAY(q_cont, vlevel1d)
        CALL POPREAL8ARRAY(beta_theta, vlevel1d)
        CALL POPREAL8ARRAY(theta_down, vlevel1d)
        CALL POPREAL8(d)
        CALL POPREAL8(max_dtheta)
        CALL POPREAL8(dth_m)
        dthetab = 0.0_8
        CALL POPREAL8(sum_act_zu2_p2)
        CALL POPREAL8(sum_act_zu2)
        z_u2b = 0.0_8
        temp4 = z_u2**8.0D0 + 1.0D0
        z_u2b = -(8.0D0 * z_u2**7.0D0 * act_zu2b / temp4**2)
        tempb4 = z_u2b / (ht - hb)
        tempb9 = -(SUM((gph1d * 2.0D0 - ht - hb) * tempb4) / (ht - hb))
        htb = htb + tempb9 - SUM(tempb4)
        hbb = -SUM(tempb4) - tempb9
        CALL POPREAL8(act_cape)
        tempb9 = (1.0 - TANH((cape + cin) / 1.0D03 - 2.5D0)**2) * act_capeb / (1.0D03 *&
  &       2.0D0)
        capeb = tempb9
        cinb = tempb9
        CALL POPREAL8(cape)
        result1b = capeb / 2.0D0
        act_dth_capeb = 0.0_8
        tempb12 = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * result1b
        act_dth_capeb(2:vlevel1d) = act_dth_capeb(2:vlevel1d) + tempb12
        act_dth_capeb(1:vlevel1d - 1) = act_dth_capeb(1:vlevel1d - 1) + &
  &       tempb12
        act_zub = 0.0_8
        act_zub = dtheta * act_dth_capeb
        z_ub = 0.0_8
        temp4 = z_u**8.0D0 + 1.0D0
        z_ub = -(8.0D0 * z_u**7.0D0 * act_zub / temp4**2)
        tempb4 = z_ub / (ht - lfc)
        tempb9 = -(SUM((gph1d * 2.0D0 - ht - lfc) * tempb4) / (ht - lfc))
        htb = htb + tempb9 - SUM(tempb4)
        lfcb = -SUM(tempb4) - tempb9
        result1b = cinb / 2.0D0
        act_dth_cinb = 0.0_8
        tempb12 = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * result1b
        act_dth_cinb(2:vlevel1d) = act_dth_cinb(2:vlevel1d) + tempb12
        act_dth_cinb(1:vlevel1d - 1) = act_dth_cinb(1:vlevel1d - 1) + tempb12
        dthetab = act_zu2 * act_dth_db + act_zu * act_dth_capeb + act_cin *&
  &       act_dth_cinb
        CALL POPREAL8ARRAY(act_zu, vlevel1d)
        CALL POPREAL8ARRAY(z_u, vlevel1d)
        CALL POPREAL8(cin)
        CALL POPREAL8(result1)
        act_cinb = 0.0_8
        act_cinb = dtheta * act_dth_cinb
        CALL POPREAL8ARRAY(act_cin, vlevel1d)
        CALL POPREAL8(act_p500)
        ptb = -((1.0 - TANH((5.0D02 - pt) / 5.0D01)**2) * act_p500b / (5.0D01 * 2.0D0)&
  &       )
        CALL POPREAL8(act_dz)
        tempb9 = (1.0 - TANH((ht - lfc - 3.0D03) / 5.0D02)**2) * act_dzb / (5.0D02 *&
  &       2.0D0)
        lfcb = lfcb + SUM((1.0 - TANH((lfc - gph1d) / 5.0D02)**2) * act_cinb) / (&
  &       5.0D02 * 2.0D0) - tempb9
        htb = htb + tempb9
        CALL POPREAL8(lfc)
        result1b = lfcb / result2
        result2b = -(result1 * lfcb / result2**2)
        dgphm = gph1dm2(2:size_3m) - gph1dm2(1:size_3m - 1)
        act_lfc2b = 0.0_8
        CALL POPREAL8(result2)
        act_lfc2b(1:size_3m - 1) = act_lfc2b(1:size_3m - 1) + dgphm * result2b
        act_lfc2b(2:size_3m) = act_lfc2b(2:size_3m) + dgphm * result2b
        CALL POPREAL8(result1)
        act_lfc2b(1:size_3m - 1) = act_lfc2b(1:size_3m - 1) + gph1dm2(1:&
  &       size_3m - 1) * dgphm * result1b
        act_lfc2b(2:size_3m) = act_lfc2b(2:size_3m) + gph1dm2(2:size_3m) *&
  &       dgphm * result1b
        CALL POPREAL8(ht)
        result1b = htb / result2
        result2b = -(result1 * htb / result2**2)
        act_pt = 1.0D0 / (1.0D0 + (gph1dm2 - htt)**4.0D0 / 1.0D08)
        act_ptb = 0.0_8
        CALL POPREAL8(result2)
        act_ptb(1:size_3m - 1) = act_ptb(1:size_3m - 1) + dgphm * result2b
        act_ptb(2:size_3m) = act_ptb(2:size_3m) + dgphm * result2b
        CALL POPREAL8(result1)
        act_ptb(1:size_3m - 1) = act_ptb(1:size_3m - 1) + gph1dm2(1:size_3m - 1)&
                                &       * dgphm * result1b
        act_ptb(2:size_3m) = act_ptb(2:size_3m) + gph1dm2(2:size_3m) * dgphm&
                            &       * result1b
        CALL POPREAL8(pt)
        result1b = ptb / result2
        result2b = -(result1 * ptb / result2**2)
        CALL POPREAL8(result2)
        act_ptb(1:size_3m - 1) = act_ptb(1:size_3m - 1) + dgphm * result2b
        act_ptb(2:size_3m) = act_ptb(2:size_3m) + dgphm * result2b
        pm2b = 0.0_8
        CALL POPREAL8(result1)
        tempb13 = dgphm * result1b
        act_ptb(1:size_3m - 1) = act_ptb(1:size_3m - 1) + pm2(1:size_3m - 1) *&
  &       tempb13
        pm2b(1:size_3m - 1) = pm2b(1:size_3m - 1) + act_pt(1:size_3m - 1) *&
  &       tempb13
        act_ptb(2:size_3m) = act_ptb(2:size_3m) + pm2(2:size_3m) * tempb13
        pm2b(2:size_3m) = pm2b(2:size_3m) + act_pt(2:size_3m) * tempb13
        temp14 = (gph1dm2 - lfct)**4.0D0 / 1.0D08 + 1.0D0
        lfctb = SUM((gph1dm2 - lfct)**3.0D0 * act_lfc2b / temp14**2) * 4.0D0 /&
  &       1.0D08
        temp14 = (gph1dm2 - htt)**4.0D0 / 1.0D08 + 1.0D0
        httb = SUM((gph1dm2 - htt)**3.0D0 * act_ptb / temp14**2) * 4.0D0 / 1.0D08
        CALL POPREAL8(lfct)
        tempb9 = lfctb / result2
        act_sum_ctb = result1 * tempb9
        result1b = act_sum_ct * tempb9
        result2b = -(act_sum_ct * result1 * tempb9 / result2)
        act_lfcb = 0.0_8
        CALL POPREAL8(result2)
        act_lfcb(1:size_3m - 1) = act_lfcb(1:size_3m - 1) + dgphm * result2b
        act_lfcb(2:size_3m) = act_lfcb(2:size_3m) + dgphm * result2b
        CALL POPREAL8(result1)
        act_lfcb(1:size_3m - 1) = act_lfcb(1:size_3m - 1) + gph1dm2(1:size_3m -&
  &       1) * dgphm * result1b
        act_lfcb(2:size_3m) = act_lfcb(2:size_3m) + gph1dm2(2:size_3m) *&
  &       dgphm * result1b
        CALL POPREAL8(htt)
        tempb9 = httb / result2
        act_sum_ctb = act_sum_ctb + result1 * tempb9
        result1b = act_sum_ct * tempb9
        result2b = -(act_sum_ct * result1 * tempb9 / result2)
        act_dth_ct = 1.0D0 / (1.0D0 + 5.0D03 * dtheta_m2**4.0D0)
        act_ct = act_p500_ct * act_dthz_ct * act_dth_ct
        act_ctb = 0.0_8
        CALL POPREAL8(result2)
        act_ctb(1:size_3m - 1) = act_ctb(1:size_3m - 1) + dgphm * result2b
        act_ctb(2:size_3m) = act_ctb(2:size_3m) + dgphm * result2b
        CALL POPREAL8(result1)
        act_ctb(1:size_3m - 1) = act_ctb(1:size_3m - 1) + gph1dm2(1:size_3m - 1)&
                                &       * dgphm * result1b
        act_ctb(2:size_3m) = act_ctb(2:size_3m) + gph1dm2(2:size_3m) * dgphm&
                            &       * result1b
        act_dthz_lfcb = 0.0_8
        act_dth_lfcb = 0.0_8
        act_p500_lfcb = 0.0_8
        act_p500_lfcb = act_dthz_lfc * act_dth_lfc * act_lfcb
        act_dthz_lfcb = act_p500_lfc * act_dth_lfc * act_lfcb
        act_dth_lfcb = act_p500_lfc * act_dthz_lfc * act_lfcb
        CALL POPREAL8(act_sum_ct)
        temp2 = -(1.0D01 * SUM(act_ct))
        temp12 = EXP(temp2) + 1.0D0
        act_ctb = act_ctb + 1.0D01 * EXP(temp2) * 2.0D0 * act_sum_ctb / temp12**2
        act_p500_ctb = 0.0_8
        act_dthz_ctb = 0.0_8
        act_dth_ctb = 0.0_8
        act_p500_ctb = act_dthz_ct * act_dth_ct * act_ctb
        act_dthz_ctb = act_p500_ct * act_dth_ct * act_ctb
        act_dth_ctb = act_p500_ct * act_dthz_ct * act_ctb
        CALL POPREAL8ARRAY(act_dth_lfc, size_3m)
        temp13 = 5.0D03 * dtheta_m2**4.0D0 + 1.0D0
        dtheta_m2b = dtheta_m2b - 4.0D0 * dtheta_m2**3.0D0 * 5.0D03 *&
  &       act_dth_lfcb / temp13**2
        CALL POPREAL8ARRAY(act_dthz_lfc, size_3m)
        dtheta_dz2b = dtheta_dz2b + 1.0D04 * (1.0 - TANH(1.0D04 * dtheta_dz2)**2&
  &       ) * act_dthz_lfcb / 2.0D0 - 3.0D04 * (1.0 - TANH(3.0D04 * dtheta_dz2)**2) *&
  &       act_dthz_ctb / 2.0D0
        temp13 = 5.0D03 * dtheta_m2**4.0D0 + 1.0D0
        dtheta_m2b = dtheta_m2b - 4.0D0 * dtheta_m2**3.0D0 * 5.0D03 *&
  &       act_dth_ctb / temp13**2
        CALL POPREAL8ARRAY(act_dthz_ct, size_3m)
        CALL POPREAL8ARRAY(act_p500_lfc, size_3m)
        pm2b = pm2b + (1.0 - TANH((pm2 - 5.0D02) / 8.0D01)**2) * act_p500_lfcb / (&
  &       8.0D01 * 2.0D0) - (1.0 - TANH((5.0D02 - pm2) / 8.0D01)**2) * act_p500_ctb /&
  &       (8.0D01 * 2.0D0)
        CALL POPREAL8ARRAY(act_p500_ct, size_3m)
        CALL POPREAL8ARRAY(pm2, size_3m)
        pm2tb = pm2tb + EXP(pm2t) * pm2b
        CALL POPREAL8ARRAY(pm2t, size_3m)
        CALL INTERP1D_B(gph1dm, pm, pmb, vlevel1d2, gph1dm2, pm2t, pm2tb)
        dtheta_dz = (dtheta(2:vlevel1d) - dtheta(1:vlevel1d - 1)) / (gph1d(2:&
  &       vlevel1d) - gph1d(1:vlevel1d - 1))
        CALL POPREAL8ARRAY(dtheta_dz2, size_3m)
        CALL INTERP1D_B(gph1dm, dtheta_dz, dtheta_dzb, vlevel1d2, gph1dm2&
  &               , dtheta_dz2, dtheta_dz2b)
        dtheta_m = (dtheta(2:vlevel1d) + dtheta(1:vlevel1d - 1)) / 2.0D0
        CALL POPREAL8ARRAY(dtheta_m2, size_3m)
        CALL INTERP1D_B(gph1dm, dtheta_m, dtheta_mb, vlevel1d2, gph1dm2, &
  &               dtheta_m2, dtheta_m2b)
        CALL POPREAL8ARRAY(pm, vlevel1d - 1)
        pres1db(2:vlevel1d) = pres1db(2:vlevel1d) + pmb / (pres1d(2:vlevel1d&
  &       ) * 2.0D0)
        pres1db(1:vlevel1d - 1) = pres1db(1:vlevel1d - 1) + pmb / (pres1d(1:&
  &       vlevel1d - 1) * 2.0D0)
        CALL POPREAL8ARRAY(dtheta_m, vlevel1d - 1)
        dthetab(2:vlevel1d) = dthetab(2:vlevel1d) + dtheta_mb / 2.0D0
        dthetab(1:vlevel1d - 1) = dthetab(1:vlevel1d - 1) + dtheta_mb / 2.0D0
        CALL POPREAL8ARRAY(dtheta_dz, vlevel1d - 1)
        tempb12 = dtheta_dzb / (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1))
        dthetab(2:vlevel1d) = dthetab(2:vlevel1d) + tempb12
        dthetab(1:vlevel1d - 1) = dthetab(1:vlevel1d - 1) - tempb12
        theta1db = theta_downb - d_theta_conb - dthetab
        CALL POPREAL8ARRAY(dtheta, vlevel1d)
        theta_cb = theta_cb + dthetab
        CALL POPINTEGER4(ad_from)
        DO k = vlevel1d - 1, ad_from, -1
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(theta_c(k + 1))
            temp2 = 1.0D03 / pres1d(k + 1)
            temp_cb(k + 1) = temp_cb(k + 1) + temp2**k_d * theta_cb(k + 1)
            IF (.NOT. (temp2 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT&
  &             (k_d)))) pres1db(k + 1) = pres1db(k + 1) - temp2 * k_d * temp2**(&
  &             k_d - 1) * temp_c(k + 1) * theta_cb(k + 1) / pres1d(k + 1)
            theta_cb(k + 1) = 0.0_8
            CALL POPREAL8(temp_c(k + 1))
            tempt1b = temp_cb(k + 1)
            tempb9 = (gph1d(k + 1) - gph1d(k)) * temp_cb(k + 1) / 2.0D0
            temp_cb(k + 1) = 0.0_8
            gamma_m1b = tempb9
            gamma_m2b = tempb9
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              temp12 = tempt2**2.0D0
              temp11 = cp * r_d * pres1d(k + 1)
              temp10 = temp11 * temp12
              temp9 = lv**2.0D0 * epsw_r**2.0D0
              temp8 = temp9 * est2 / temp10 + 1.0D0
              temp6 = pres1d(k + 1) * r_d * tempt2
              temp5 = est2 / temp6
              tempb11 = -(gamma_d * gamma_m2b / temp8)
              tempb5 = lv * epsw_r * tempb11 / temp6
              tempb3 = -(temp9 * (lv * epsw_r * temp5 + 1.0D0) * tempb11 / (temp10 *&
  &             temp8))
              est2b = tempb3 + tempb5
              tempb8 = -(est2 * tempb3 / temp10)
              tempb10 = -(temp5 * tempb5)
              pres1db(k + 1) = pres1db(k + 1) + cp * r_d * temp12 * tempb8 + r_d *&
  &             tempt2 * tempb10
              CALL POPREAL8(est2)
              temp12 = (tempt2 - tk) / (tempt2 - 3.011D01)
              tempb9 = 1.7625D01 * EXP(1.7625D01 * temp12) * 6.1094D0 * est2b / (&
  &             tempt2 - 3.011D01)
              tempt2b = 2.0D0 * tempt2 * temp11 * tempb8 + r_d * pres1d(k + 1) *&
  &             tempb10 + (1.0 - temp12) * tempb9
            ELSE
              tempt2b = 0.0_8
            END IF
            tempb3 = epsw_r * q_cb(k) / (pres1d(k) - est1)
            tempb5 = -(est1 * tempb3 / (pres1d(k) - est1))
            gamma_m1b = gamma_m1b + (gph1d(k + 1) - gph1d(k)) * tempt2b
            temp5 = tempt1**2.0D0
            temp3 = cp * r_d * pres1d(k)
            temp6 = temp3 * temp5
            temp7 = lv**2.0D0 * epsw_r**2.0D0
            temp8 = temp7 * est1 / temp6 + 1.0D0
            temp10 = pres1d(k) * r_d * tempt1
            temp11 = est1 / temp10
            tempb6 = -(gamma_d * gamma_m1b / temp8)
            tempb9 = -(temp7 * (lv * epsw_r * temp11 + 1.0D0) * tempb6 / (temp6 * temp8)&
  &           )
            tempb10 = -(est1 * tempb9 / temp6)
            CALL POPREAL8(tempt2)
            tempt1b = tempt1b + tempt2b + 2.0D0 * tempt1 * temp3 * tempb10
            tempb7 = lv * epsw_r * tempb6 / temp10
            est1b = tempb9 + tempb7 + tempb3 - tempb5
            tempb8 = -(temp11 * tempb7)
            pres1db(k) = pres1db(k) + cp * r_d * temp5 * tempb10 + r_d * tempt1 *&
  &           tempb8 + tempb5
            q_cb(k) = 0.0_8
            CALL POPREAL8(est1)
            temp3 = (tempt1 - tk) / (tempt1 - 3.011D01)
            tempb3 = 1.7625D01 * EXP(1.7625D01 * temp3) * 6.1094D0 * est1b / (tempt1&
  &           - 3.011D01)
            tempt1b = tempt1b + r_d * pres1d(k) * tempb8 + (1.0 - temp3) * tempb3
          ELSE
            q_cb(k) = 0.0_8
            tempt1b = 0.0_8
          END IF
          CALL POPREAL8(tempt1)
          temp_cb(k) = temp_cb(k) + tempt1b
        END DO
        tempb3 = cp * hbb / g
        CALL POPREAL8(temp_c(k_bot))
        tbb = temp_cb(k_bot) - tempb3
        temp_cb(k_bot) = 0.0_8
        CALL POPREAL8ARRAY(theta_c(1:k_bot), k_bot)
        theta1db(1) = theta1db(1) + SUM(theta_cb(1:k_bot))
        theta_cb(1:k_bot) = 0.0_8
        qvapor1db = qvapor1db + q_cb
        CALL POPBOOLEANARRAY(mask, vlevel1d)
        CALL POPREAL8(hb)
        temp1dmeanb = tempb3
        qvapor1dmeanb = 0.0_8
        pres1dmeanb = 0.0_8
        DO keps = 5, 1, -1
          CALL POPREAL8(tb)
          tb1b = tbb
          ftsb = -(tb1b / dfts)
          dftsb = fts * tb1b / dfts**2
          CALL POPREAL8(dfts)
          tempb3 = r_k_d * dftsb / tb
          tbb = tb1b + r_k_d * dftsb / tb + (1.0 - (a + tb) / tb) * tempb3 + (DLOG(tb)&
  &         * r_k_d + (a + tb) * r_k_d / tb + DLOG(qvapor1dmean) + DLOG(pres1dmean) -&
  &         r_k_d * DLOG(temp1dmean) - DLOG(6.1094D0 * (epsw_r + qvapor1dmean)) -&
  &         1.7625D01) * ftsb
          CALL POPREAL8(fts)
          tempb2 = tb * ftsb
          tempb1 = a * ftsb
          qvapor1dmeanb = qvapor1dmeanb + (1.0 / qvapor1dmean - 1.0 / (epsw_r +&
  &         qvapor1dmean)) * dftsb + (1.0 / qvapor1dmean - 1.0 / (epsw_r +&
  &         qvapor1dmean)) * tempb1 + (1.0 / qvapor1dmean - 1.0 / (epsw_r +&
  &         qvapor1dmean)) * tempb2
          pres1dmeanb = pres1dmeanb + dftsb / pres1dmean + tempb1 / pres1dmean&
  &         + tempb2 / pres1dmean
          temp1dmeanb = temp1dmeanb - r_k_d * dftsb / temp1dmean - r_k_d *&
  &         tempb1 / temp1dmean - r_k_d * tempb2 / temp1dmean
        END DO
        temp1dmeanb = temp1dmeanb + tbb
        CALL POPREAL8(temp1dmean)
        temp1db(1:3) = temp1db(1:3) + temp1dmeanb / 3.0D0
        CALL POPREAL8(pres1dmean)
        pres1db(1:3) = pres1db(1:3) + pres1dmeanb / 3.0D0
        CALL POPREAL8(qvapor1dmean)
        qvapor1db(1:3) = qvapor1db(1:3) + qvapor1dmeanb / 3.0D0
        k_ref = vlevel / 2
        theta_eb = 0.0_8
        CALL POPREAL8(act_dthetae)
        tempb3 = (1.0 - TANH(2.0D0 * (theta_e(1) - theta_e(k_ref) - 1.0D0))**2) *&
  &       act_dthetaeb
        theta_eb(1) = theta_eb(1) + tempb3
        theta_eb(k_ref) = theta_eb(k_ref) - tempb3
        tlclb = 0.0_8
        CALL POPREAL8ARRAY(theta_e, vlevel1d)
        temp4 = qvapor1d / (cp * tlcl)
        theta1db = theta1db + DEXP(lv * temp4) * theta_eb
        tempb4 = lv * DEXP(lv * temp4) * theta1d * theta_eb / (cp * tlcl)
        qvapor1db = qvapor1db + tempb4
        tlclb = -(cp * temp4 * tempb4)
        DO k = vlevel1d, 1, -1
          DO keps = 5, 1, -1
            temp1 = 6.1094D0 * (epsw_r + qvapor1d(k))
            CALL POPREAL8(tlcl(k))
            tlcl1b = tlclb(k)
            ftsb = -(tlcl1b / dfts)
            dftsb = fts * tlcl1b / dfts**2
            CALL POPREAL8(dfts)
            tempb3 = dftsb / (k_d * tlcl(k))
            tlclb(k) = tlcl1b + dftsb / (tlcl(k) * k_d) + (1.0 - (a + tlcl(k)) /&
  &           tlcl(k)) * tempb3 + (DLOG(tlcl(k)) / k_d + (a + tlcl(k)) / (tlcl(k) *&
  &           k_d) + DLOG(qvapor1d(k)) + DLOG(pres1d(k)) - DLOG(temp1d(k)) / k_d -&
  &           DLOG(temp1) - 17.625D0) * ftsb
            CALL POPREAL8(fts)
            tempb1 = tlcl(k) * ftsb
            tempb2 = a * ftsb
            qvapor1db(k) = qvapor1db(k) + (1.0 / qvapor1d(k) - 1.0 / (epsw_r +&
  &           qvapor1d(k))) * dftsb + (1.0 / qvapor1d(k) - 1.0 / (epsw_r + qvapor1d(&
  &           k))) * tempb2 + (1.0 / qvapor1d(k) - 6.1094D0 / temp1) * tempb1
            pres1db(k) = pres1db(k) + dftsb / pres1d(k) + tempb2 / pres1d(k) +&
  &           tempb1 / pres1d(k)
            temp1db(k) = temp1db(k) - dftsb / (temp1d(k) * k_d) - tempb2 / (&
  &           temp1d(k) * k_d) - tempb1 / (temp1d(k) * k_d)
          END DO
        END DO
        CALL POPREAL8ARRAY(tlcl, vlevel1d)
        temp1db = temp1db + tlclb
        c_qb(1) = 0.0_8
        c_thetab(1) = 0.0_8
        DO kgph = size_3m, 1, -1
          CALL POPREAL8(gph1dm2(kgph))
        END DO
        CALL POPREAL8ARRAY(gph1dm, vlevel1d - 1)
        CALL POPREAL8ARRAY(rhod1d, vlevel1d)
        rhodb(2:vlevel, i) = rhodb(2:vlevel, i) + rhod1db
        CALL POPREAL8ARRAY(gph1d, vlevel1d)
        CALL POPREAL8ARRAY(qvapor1d, vlevel1d)
        qvaporb(2:vlevel, i) = qvaporb(2:vlevel, i) + qvapor1db
        CALL POPREAL8ARRAY(temp1d, vlevel1d)
        tempb(2:vlevel, i) = tempb(2:vlevel, i) + temp1db
        CALL POPREAL8ARRAY(theta1d, vlevel1d)
        thetab(2:vlevel, i) = thetab(2:vlevel, i) + theta1db
        CALL POPREAL8ARRAY(pres1d, vlevel1d)
        presb(2:vlevel, i) = presb(2:vlevel, i) + pres1db / 1.0D02
      END IF
    END DO
    rhodb = rhodb + qvapor * wwnd * qwb + qvapor * vwnd * qvb + qvapor * uwnd * qub
    qvaporb = qvaporb + rhod * wwnd * qwb + rhod * vwnd * qvb + rhod * uwnd * qub
    wwndb = wwndb + rhod * qvapor * qwb
    vwndb = vwndb + rhod * qvapor * qvb
    uwndb = uwndb + rhod * qvapor * qub
    temp0 = r_d * temp * (qvapor + 1)
    tempb0 = -(pres * rhodb / temp0**2)
    tempb = tempb + r_d * (qvapor + 1) * tempb0
    WHERE (pres / 1.0D05 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT(k_d)&
  &     ))
      presb = presb + rhodb / temp0
    ELSEWHERE
      presb = presb + rhodb / temp0 + k_d * (pres / 1.0D05)**(k_d - 1) * theta * tempb&
  &     / 1.0D05
    END WHERE
    qvaporb = qvaporb + r_d * temp * tempb0
    thetab = thetab + (pres / 1.0D05)**k_d * tempb
  END SUBROUTINE CUMFWD_B
END MODULE CumFwdB_m
