!  Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 31 May 2021 11:17
!
!  Differentiation of divergence in reverse (adjoint) mode:
!   gradient     of useful results: divgc
!   with respect to varying inputs: fv_c fv_n fv_s divgc fu_c fu_e
!                fw fu_w

!!--------------------------------------------------------------------------------------------------
! PROJECT           : MOTOR-DA
! AFFILIATION       : Guangdong-HongKong-Macao Greater Bay Area Weather
! Research Center for Monitoring Warning and Forecasting (GBA-MWF)
!                     Shenzhen Institute of Meteorological Innovation
! AUTOHR(S)         : Jilong CHEN
! VERSION           : V 0.0
! HISTORY           :
!   Created by Jilong CHEN (jchen@link.cuhk.edu.hk), 2021/1/26, @GBA-MWF,
!   Shenzhen
!!--------------------------------------------------------------------------------------------------

!> @brief
!!

MODULE divergenceB_m

CONTAINS

  SUBROUTINE DIVERGENCE_B(fu_c, fu_cb, fu_w, fu_wb, fu_e, fu_eb, fv_c, &
      & fv_cb, fv_s, fv_sb, fv_n, fv_nb, fw, fwb, sigma, ztop, topo_c, topo_w&
      & , topo_e, topo_s, topo_n, dist_we, dist_sn, vlevel, divgc, divgcb)
    IMPLICIT NONE
    REAL*8, DIMENSION(:), INTENT(IN) :: fu_c, fu_e, fu_w, fv_c, fv_n, fv_s&
  & , fw, sigma
    REAL*8, DIMENSION(:) :: fu_cb, fu_eb, fu_wb, fv_cb, fv_nb, fv_sb, fwb
    REAL*8, INTENT(IN) :: ztop, topo_c, topo_w, topo_e, topo_s, topo_n, &
  & dist_we, dist_sn
    INTEGER*4, INTENT(IN) :: vlevel
    REAL*8 :: h_0(vlevel - 2), h_n1(vlevel - 2), h_p1(vlevel - 2), par_fusigma(&
  & vlevel), par_fvsigma(vlevel), par_fwsigma(vlevel)
    REAL*8 :: par_fusigmab(vlevel), par_fvsigmab(vlevel), par_fwsigmab(&
  & vlevel)
    REAL*8, INTENT(INOUT) :: divgc(:)
    REAL*8, INTENT(INOUT) :: divgcb(:)
    REAL*8 :: rat, par_temp, par_sigmax, par_sigmay
    INTRINSIC SIZE
    REAL*8 :: tempb
    REAL*8 :: tempb0
    REAL*8, DIMENSION(vlevel - 2) :: tempb1
    REAL*8, DIMENSION(vlevel - 2) :: tempb2
    rat = ztop / (ztop - topo_c)

    par_temp = 1 / (ztop - topo_c)**2.0D0
    par_sigmax = par_temp * (topo_e - topo_w) / 2.0D0 / dist_we
    par_sigmay = par_temp * (topo_n - topo_s) / 2.0D0 / dist_sn

    h_0 = (2.0D0 * sigma(2:vlevel - 1) - sigma(1:vlevel - 2) - sigma(3:vlevel)) / (&
  &   sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:vlevel&
  &   - 1))
    ! n represents negative
    h_n1 = (sigma(3:vlevel) - sigma(2:vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(2:&
  &   vlevel - 1)) / (sigma(3:vlevel) - sigma(1:vlevel - 2))
    ! p represents positive
    h_p1 = (sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:&
  &   vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(3:vlevel))
    fv_nb = 0.0_8
    fv_sb = 0.0_8
    fu_eb = 0.0_8
    fu_wb = 0.0_8
    tempb0 = divgcb(vlevel) / (dist_we * 2.0D0)
    tempb = divgcb(vlevel) / (dist_sn * 2.0D0)
    divgcb(vlevel) = 0.0_8
    fv_nb(vlevel) = fv_nb(vlevel) + tempb
    fv_sb(vlevel) = fv_sb(vlevel) - tempb
    fu_eb(vlevel) = fu_eb(vlevel) + tempb0
    fu_wb(vlevel) = fu_wb(vlevel) - tempb0
    par_fvsigmab = 0.0_8
    par_fusigmab = 0.0_8
    par_fwsigmab = 0.0_8
    tempb1 = divgcb(2:vlevel - 1) / (dist_we * 2.0D0)
    tempb2 = divgcb(2:vlevel - 1) / (dist_sn * 2.0D0)
    par_fusigmab(2:vlevel - 1) = par_fusigmab(2:vlevel - 1) - par_sigmax *&
  &   divgcb(2:vlevel - 1)
    par_fwsigmab(2:vlevel - 1) = par_fwsigmab(2:vlevel - 1) + rat * divgcb(2:&
  &   vlevel - 1)
    par_fvsigmab(2:vlevel - 1) = par_fvsigmab(2:vlevel - 1) - par_sigmay *&
  &   divgcb(2:vlevel - 1)
    divgcb(2:vlevel - 1) = 0.0_8
    fv_nb(2:vlevel - 1) = fv_nb(2:vlevel - 1) + tempb2
    fv_sb(2:vlevel - 1) = fv_sb(2:vlevel - 1) - tempb2
    fu_eb(2:vlevel - 1) = fu_eb(2:vlevel - 1) + tempb1
    fu_wb(2:vlevel - 1) = fu_wb(2:vlevel - 1) - tempb1
    tempb = divgcb(1) / (dist_we * 2.0D0)
    tempb0 = divgcb(1) / (dist_sn * 2.0D0)
    divgcb(1) = 0.0_8
    fv_nb(1) = fv_nb(1) + tempb0
    fv_sb(1) = fv_sb(1) - tempb0
    fu_eb(1) = fu_eb(1) + tempb
    fu_wb(1) = fu_wb(1) - tempb
    par_fwsigmab(vlevel) = 0.0_8
    fwb = 0.0_8
    fwb(2:vlevel - 1) = fwb(2:vlevel - 1) + h_0 * par_fwsigmab(2:vlevel - 1)
    fwb(3:vlevel) = fwb(3:vlevel) + h_p1 * par_fwsigmab(2:vlevel - 1)
    fwb(1:vlevel - 2) = fwb(1:vlevel - 2) + h_n1 * par_fwsigmab(2:vlevel - 1)
    par_fvsigmab(vlevel) = 0.0_8
    fv_cb = 0.0_8
    fv_cb(2:vlevel - 1) = fv_cb(2:vlevel - 1) + h_0 * par_fvsigmab(2:vlevel - 1)
    fv_cb(3:vlevel) = fv_cb(3:vlevel) + h_p1 * par_fvsigmab(2:vlevel - 1)
    fv_cb(1:vlevel - 2) = fv_cb(1:vlevel - 2) + h_n1 * par_fvsigmab(2:vlevel - 1)
    par_fusigmab(vlevel) = 0.0_8
    fu_cb = 0.0_8
    fu_cb(2:vlevel - 1) = fu_cb(2:vlevel - 1) + h_0 * par_fusigmab(2:vlevel - 1)
    fu_cb(3:vlevel) = fu_cb(3:vlevel) + h_p1 * par_fusigmab(2:vlevel - 1)
    fu_cb(1:vlevel - 2) = fu_cb(1:vlevel - 2) + h_n1 * par_fusigmab(2:vlevel - 1)

  END SUBROUTINE DIVERGENCE_B

END MODULE divergenceB_m
