!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 31 May 2021 11:17
!
!  Differentiation of rk4 in forward (tangent) mode:
!   variations   of useful results: precip qvapor_out theta_out
!   with respect to varying inputs: precip qvapor_out vwnd_out
!                pres_out wwnd_out theta_out uwnd_out
!   RW status of diff variables: precip:in-out qvapor_out:in-out
!                vwnd_out:in pres_out:in wwnd_out:in theta_out:in-out
!                uwnd_out:in

!!--------------------------------------------------------------------------------------------------
! PROJECT           : MOTOR-DA
! AFFILIATION       : Guangdong-HongKong-Macao Greater Bay Area Weather
! Research Center for Monitoring Warning and Forecasting (GBA-MWF)
!                     Shenzhen Institute of Meteorological Innovation
! AUTOHR(S)         : Jilong CHEN
! VERSION           : V 0.0
! HISTORY           :
!   Created by Jilong CHEN (jchen@link.cuhk.edu.hk), 2021/1/26, @GBA-MWF,
!   Shenzhen
!!--------------------------------------------------------------------------------------------------

!> @brief
!!
MODULE RK4D_m
  USE parameters_m, ONLY: g, cp, Lv, k_d, r_k_d, epsw_r, gamma_d, r_d, TK
CONTAINS

  SUBROUTINE RK4_D(uwnd_out, uwnd_outd, vwnd_out, vwnd_outd, wwnd_out, &
    & wwnd_outd, theta_out, theta_outd, qvapor_out, qvapor_outd, pres_out, &
    & pres_outd, precip, precipd, size_q_dim1, size_q_dim2, size_q_dim3, &
    & cu_dt, ztop, cell_dist, cell_stcl, gph, cell_type, sigma, topo, &
    & num_cell, num_icell, size_3m)
    IMPLICIT NONE
    INTEGER*4, INTENT(IN) :: size_q_dim1, size_q_dim2, size_q_dim3, &
  & cell_stcl(:, :), cell_type(:), num_cell, num_icell, size_3m
    REAL*8, DIMENSION(size_q_dim1, size_q_dim2, size_q_dim3), INTENT(INOUT&
  & ) :: uwnd_out, vwnd_out, wwnd_out, theta_out, qvapor_out, pres_out
    REAL*8, INTENT(INOUT) :: precip(1, size_q_dim2, size_q_dim3)
    REAL*8, DIMENSION(size_q_dim1, size_q_dim2, size_q_dim3), INTENT(INOUT&
  & ) :: uwnd_outd, vwnd_outd, wwnd_outd, theta_outd, qvapor_outd, &
  & pres_outd
    REAL*8, INTENT(INOUT) :: precipd(1, size_q_dim2, size_q_dim3)
    REAL*8, INTENT(IN) :: cell_dist(9, size_q_dim2), gph(size_q_dim1, size_q_dim2), &
  & sigma(size_q_dim1), topo(size_q_dim2), cu_dt, ztop
    REAL*8 :: dthdt(size_q_dim1, size_q_dim2, 4), dqdt(size_q_dim1, &
  & size_q_dim2, 4), theta_t(size_q_dim1, size_q_dim2), qvapor_t(&
  & size_q_dim1, size_q_dim2), dprecipdt(size_q_dim2, 4)
    REAL*8 :: dthdtd(size_q_dim1, size_q_dim2, 4), dqdtd(size_q_dim1, &
  & size_q_dim2, 4), theta_td(size_q_dim1, size_q_dim2), qvapor_td(&
  & size_q_dim1, size_q_dim2), dprecipdtd(size_q_dim2, 4)
    INTEGER*4 :: it1, it2, vlevel, vlevel1d
    INTRINSIC SIZE

    vlevel = size_q_dim1
    vlevel1d = vlevel - 1

    dthdt = 0.0D0
    dqdt = 0.0D0
    dprecipdt = 0.0D0
    dqdtd = 0.0_8
    dthdtd = 0.0_8
    dprecipdtd = 0.0_8
    DO it1 = 1, size_q_dim3 - 1
      DO it2 = 1, 4
        IF (it2 .EQ. 1) THEN
          theta_td = theta_outd(:, :, it1)
          theta_t = theta_out(:, :, it1)
          qvapor_td = qvapor_outd(:, :, it1)
          qvapor_t = qvapor_out(:, :, it1)
        ELSE IF (it2 .EQ. 4) THEN
          theta_td = theta_outd(:, :, it1) + cu_dt * dthdtd(:, :, it2 - 1)
          theta_t = theta_out(:, :, it1) + cu_dt * dthdt(:, :, it2 - 1)
          qvapor_td = qvapor_outd(:, :, it1) + cu_dt * dqdtd(:, :, it2 - 1)
          qvapor_t = qvapor_out(:, :, it1) + cu_dt * dqdt(:, :, it2 - 1)
        ELSE
          theta_td = theta_outd(:, :, it1) + cu_dt * dthdtd(:, :, it2 - 1) /&
  &         2.0D0
          theta_t = theta_out(:, :, it1) + cu_dt * dthdt(:, :, it2 - 1) / 2.0D0
          qvapor_td = qvapor_outd(:, :, it1) + cu_dt * dqdtd(:, :, it2 - 1) /&
  &         2.0D0
          qvapor_t = qvapor_out(:, :, it1) + cu_dt * dqdt(:, :, it2 - 1) / 2.0D0
        END IF

        CALL CUMFWD_D(uwnd_out(:, :, it1), uwnd_outd(:, :, it1), vwnd_out(&
  &             :, :, it1), vwnd_outd(:, :, it1), wwnd_out(:, :, it1), &
  &             wwnd_outd(:, :, it1), pres_out(:, :, it1), pres_outd(:, :&
  &             , it1), theta_t, theta_td, qvapor_t, qvapor_td, ztop, &
  &             cell_dist, cell_stcl, gph, cell_type, sigma, topo, vlevel&
  &             , vlevel1d, size_3m, num_cell, num_icell, dthdt(:, :, it2), dthdtd(:&
  &             , :, it2), dqdt(:, :, it2), dqdtd(:, :, it2), dprecipdt(:&
  &             , it2), dprecipdtd(:, it2))

      END DO

      theta_outd(:, :, it1 + 1) = theta_outd(:, :, it1) + cu_dt * (dthdtd(:, :&
  &     , 1) + 2.0D0 * dthdtd(:, :, 2) + 2.0D0 * dthdtd(:, :, 3) + dthdtd(:, :, 4)) /&
  &     6.0D0
      theta_out(:, :, it1 + 1) = theta_out(:, :, it1) + cu_dt * (dthdt(:, :, 1&
  &     ) + 2.0D0 * dthdt(:, :, 2) + 2.0D0 * dthdt(:, :, 3) + dthdt(:, :, 4)) / 6.0D0
      qvapor_outd(:, :, it1 + 1) = qvapor_outd(:, :, it1) + cu_dt * (dqdtd(:, &
  &     :, 1) + 2.0D0 * dqdtd(:, :, 2) + 2.0D0 * dqdtd(:, :, 3) + dqdtd(:, :, 4)) /&
  &     6.0D0
      qvapor_out(:, :, it1 + 1) = qvapor_out(:, :, it1) + cu_dt * (dqdt(:, :, &
  &     1) + 2.0D0 * dqdt(:, :, 2) + 2.0D0 * dqdt(:, :, 3) + dqdt(:, :, 4)) / 6.0D0
      precipd(1, :, it1 + 1) = precipd(1, :, it1) + cu_dt * (dprecipdtd(:, 1) +&
  &     2.0D0 * dprecipdtd(:, 2) + 2.0D0 * dprecipdtd(:, 3) + dprecipdtd(:, 4)) /&
  &     6.0D0
      precip(1, :, it1 + 1) = precip(1, :, it1) + cu_dt * (dprecipdt(:, 1) +&
  &     2.0D0 * dprecipdt(:, 2) + 2.0D0 * dprecipdt(:, 3) + dprecipdt(:, 4)) / 6.0D0
    END DO
  END SUBROUTINE RK4_D

  SUBROUTINE CUMFWD_D(uwnd, uwndd, vwnd, vwndd, wwnd, wwndd, pres, presd, &
    & theta, thetad, qvapor, qvapord, ztop, cell_dist, cell_stcl, gph, &
    & cell_type, sigma, topo, vlevel, vlevel1d, size_3m, num_cell, num_icell, par_theta&
    & , par_thetad, par_q, par_qd, precip, precipd)
    IMPLICIT NONE
    INTEGER*4, INTENT(IN) :: vlevel, vlevel1d, size_3m, num_cell, num_icell, &
  & cell_stcl(:, :), cell_type(:)
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(IN) :: uwnd, vwnd, wwnd, &
  & theta, qvapor, pres, gph
    REAL(8), DIMENSION(9, num_cell), INTENT(IN) :: cell_dist
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(IN) :: uwndd, vwndd, wwndd&
  & , thetad, qvapord, presd
    REAL*8, DIMENSION(:), INTENT(IN) :: sigma, topo
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(INOUT) :: par_theta, par_q
    REAL*8, DIMENSION(vlevel, num_cell), INTENT(INOUT) :: par_thetad, &
  & par_qd
    REAL*8, DIMENSION(:), INTENT(INOUT) :: precip
    REAL*8, DIMENSION(:), INTENT(INOUT) :: precipd
    REAL*8, INTENT(IN) :: ztop
    INTEGER*4 :: i, k, k_ref, k_bot, i_e, i_w, i_n, i_s, keps, kgph, &
  & vlevel1d2
    REAL*8 :: rhod(vlevel, num_cell), qu(vlevel, num_cell), qv(vlevel, &
  & num_cell), qw(vlevel, num_cell), temp(vlevel, num_cell), uwnd1d(&
  & vlevel1d), vwnd1d(vlevel1d), wwnd1d(vlevel1d), theta1d(vlevel1d), &
  & temp1d(vlevel1d), qvapor1d(vlevel1d), pres1d(vlevel1d), gph1d(vlevel1d&
  & ), c_theta(vlevel), c_q(vlevel), tlcl(vlevel1d), beta_theta(vlevel1d)&
  & , theta_e(vlevel1d), temp_c(vlevel1d), theta_c(vlevel1d), q_c(vlevel1d&
  & ), dtheta(vlevel1d), theta_down(vlevel1d), theta_con(vlevel1d), q_con(&
  & vlevel1d), q_cont(vlevel1d), gph1dm(vlevel1d - 1), pm(vlevel1d - 1), psat(&
  & vlevel1d), qsat(vlevel1d), act_ht(vlevel1d), dtheta_dz(vlevel1d - 1), &
  & dtheta_m(vlevel1d - 1), act_cin(vlevel1d), act_dth_cin(vlevel1d), z_u(&
  & vlevel1d), act_zu(vlevel1d), act_dth_cape(vlevel1d), z_u2(vlevel1d), &
  & act_zu2(vlevel1d), act_dth_d(vlevel1d), act_dth_m(vlevel1d), divq(&
  & vlevel), qu_c(vlevel), qu_e(vlevel), qu_w(vlevel), qv_c(vlevel), qv_s(&
  & vlevel), qv_n(vlevel), qw_c(vlevel), theta1d_e(vlevel), theta1d_w(&
  & vlevel), theta1d_n(vlevel), theta1d_s(vlevel), theta1d_c(vlevel), &
  & q1d_n(vlevel), q1d_s(vlevel), q1d_e(vlevel), q1d_w(vlevel), q1d_c(&
  & vlevel), uwnd1d_c(vlevel), vwnd1d_c(vlevel), wwnd1d_c(vlevel), &
  & d_theta_con(vlevel1d), act_ht_m(vlevel1d - 1), d_theta_con_m(vlevel1d - 1)&
  & , q_con_m(vlevel1d - 1), gph1dm2(size_3m), dtheta_m2(size_3m), &
  & dtheta_dz2(size_3m), pm2t(size_3m), pm2(size_3m), act_dthz_ct(size_3m)&
  & , act_dth_ct(size_3m), act_dthz_lfc(size_3m), act_dth_lfc(size_3m), &
  & act_p500_ct(size_3m), act_p500_lfc(size_3m)
    REAL*8 :: act_ct(size_3m), act_lfc(size_3m), dgphm(size_3m - 1), act_pt(&
  & size_3m), act_lfc2(size_3m), rhod1d(vlevel1d)
    REAL*8 :: rhodd(vlevel, num_cell), qud(vlevel, num_cell), qvd(vlevel, &
  & num_cell), qwd(vlevel, num_cell), tempd(vlevel, num_cell), theta1dd(&
  & vlevel1d), temp1dd(vlevel1d), qvapor1dd(vlevel1d), pres1dd(vlevel1d), &
  & c_thetad(vlevel), c_qd(vlevel), tlcld(vlevel1d), beta_thetad(vlevel1d)&
  & , theta_ed(vlevel1d), temp_cd(vlevel1d), theta_cd(vlevel1d), q_cd(&
  & vlevel1d), dthetad(vlevel1d), theta_downd(vlevel1d), theta_cond(&
  & vlevel1d), q_cond(vlevel1d), q_contd(vlevel1d), pmd(vlevel1d - 1), psatd&
  & (vlevel1d), qsatd(vlevel1d), act_htd(vlevel1d), dtheta_dzd(vlevel1d - 1)&
  & , dtheta_md(vlevel1d - 1), act_cind(vlevel1d), act_dth_cind(vlevel1d), &
  & z_ud(vlevel1d), act_zud(vlevel1d), act_dth_caped(vlevel1d), z_u2d(&
  & vlevel1d), act_zu2d(vlevel1d), act_dth_dd(vlevel1d), act_dth_md(&
  & vlevel1d), divqd(vlevel), qu_cd(vlevel), qu_ed(vlevel), qu_wd(vlevel)&
  & , qv_cd(vlevel), qv_sd(vlevel), qv_nd(vlevel), qw_cd(vlevel), &
  & theta1d_ed(vlevel), theta1d_wd(vlevel), theta1d_nd(vlevel), theta1d_sd&
  & (vlevel), theta1d_cd(vlevel), q1d_nd(vlevel), q1d_sd(vlevel), q1d_ed(&
  & vlevel), q1d_wd(vlevel), q1d_cd(vlevel), uwnd1d_cd(vlevel), vwnd1d_cd(&
  & vlevel), wwnd1d_cd(vlevel), d_theta_cond(vlevel1d), act_ht_md(vlevel1d&
  & - 1), d_theta_con_md(vlevel1d - 1), q_con_md(vlevel1d - 1), dtheta_m2d(&
  & size_3m), dtheta_dz2d(size_3m), pm2td(size_3m), pm2d(size_3m), &
  & act_dthz_ctd(size_3m), act_dth_ctd(size_3m), act_dthz_lfcd(size_3m), &
  & act_dth_lfcd(size_3m), act_p500_ctd(size_3m), act_p500_lfcd(size_3m), &
  & act_ctd(size_3m), act_lfcd(size_3m), act_ptd(size_3m), act_lfc2d(&
  & size_3m), rhod1dd(vlevel1d)
    REAL*8 :: a, qvapor1dmean, pres1dmean, gph1dmean, temp1dmean, tb, tb1&
  & , hb, tempt1, tempt2, est1, est2, gamma_m1, gamma_m2, cape, cin, &
  & avg_dtheta, std_dtheta, max_dtheta, d, act_dz, act_dthetae, act_p500, &
  & lfct, htt, lfc, ht, pt, act_sum_ct, act_cape, tlcl1, fts, dfts, rh, &
  & act_rh, b_param, ir, act_ir, sum_act_zu2, sum_act_zu2_p2, dth_m, &
  & dth_std, q1d_sum, qsat_sum, c_star, d_c_star, d_3m
    REAL*8 :: qvapor1dmeand, pres1dmeand, temp1dmeand, tbd, tb1d, hbd, &
  & tempt1d, tempt2d, est1d, est2d, gamma_m1d, gamma_m2d, caped, cind, &
  & max_dthetad, dd, act_dzd, act_dthetaed, act_p500d, lfctd, httd, lfcd, &
  & htd, ptd, act_sum_ctd, act_caped, tlcl1d, ftsd, dftsd, rhd, act_rhd, &
  & b_paramd, ird, act_ird, sum_act_zu2d, sum_act_zu2_p2d, dth_md, &
  & dth_stdd, q1d_sumd, qsat_sumd, c_stard, d_c_stard
    INTRINSIC DLOG
    INTRINSIC DEXP
    INTRINSIC TANH
    INTRINSIC SUM
    INTRINSIC DABS
    INTRINSIC MINLOC
    INTRINSIC EXP
    INTRINSIC SQRT
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: dabs0
    REAL*8, DIMENSION(vlevel, num_cell) :: pwx1
    REAL*8, DIMENSION(vlevel, num_cell) :: pwx1d
    REAL*8, DIMENSION(vlevel, num_cell) :: pwr1
    REAL*8, DIMENSION(vlevel, num_cell) :: pwr1d
    REAL*8 :: arg1
    REAL*8 :: arg1d
    REAL*8 :: arg2
    REAL*8 :: arg2d
    REAL*8, DIMENSION(vlevel1d) :: arg10
    REAL*8, DIMENSION(vlevel1d) :: arg10d
    DOUBLE PRECISION :: arg11
    DOUBLE PRECISION :: arg11d
    DOUBLE PRECISION :: pwx10
    DOUBLE PRECISION :: pwx10d
    DOUBLE PRECISION :: pwr10
    DOUBLE PRECISION :: pwr10d
    REAL*8, DIMENSION(size_3m - 1) :: arg12
    REAL*8, DIMENSION(size_3m - 1) :: arg12d
    REAL*8, DIMENSION(size_3m - 1) :: arg20
    REAL*8, DIMENSION(size_3m - 1) :: arg20d
    REAL*8, DIMENSION(vlevel1d - 1) :: arg13
    REAL*8, DIMENSION(vlevel1d - 1) :: arg13d
    REAL*8, DIMENSION(vlevel1d) :: result1
    REAL*8 :: result2
    REAL*8 :: result2d
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: arg21
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: arg21d
    REAL*8, DIMENSION(vlevel - 2) :: arg14
    REAL*8, DIMENSION(vlevel - 2) :: arg14d
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: arg15
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: arg15d
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: pwx11
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: pwx11d
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: pwr11
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: pwr11d
    REAL*8, DIMENSION(vlevel, num_cell) :: temp0
    DOUBLE PRECISION :: temp1
    REAL*8 :: temp2
    DOUBLE PRECISION :: temp3
    REAL*8, DIMENSION(vlevel1d) :: temp4
    DOUBLE PRECISION, DIMENSION(vlevel1d) :: temp5
    REAL*8 :: temp6
    REAL*8 :: temp7
    REAL*8 :: temp8
    REAL*8 :: temp9
    REAL*8 :: temp10
    REAL*8 :: temp11
    REAL*8 :: temp12
    DOUBLE PRECISION, DIMENSION(size_3m) :: temp13
    REAL*8, DIMENSION(size_3m) :: temp14
    ! vLevel1d = vLevel - 1
    vlevel1d2 = vlevel1d - 1

    a = 2.4304D02 - tk
    pwx1d = presd / 1.0D05
    pwx1 = pres / 1.0D05
    WHERE (pwx1 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT(k_d)))
      pwr1d = 0.0_8
    ELSEWHERE
      pwr1d = k_d * pwx1**(k_d - 1) * pwx1d
    END WHERE
    pwr1 = pwx1**k_d
    tempd = pwr1 * thetad + theta * pwr1d
    temp = theta * pwr1
    temp0 = r_d * temp * (qvapor + 1)
    rhodd = (presd - pres * ((qvapor + 1) * r_d * tempd + r_d * temp * qvapord) / temp0) /&
  &   temp0
    rhod = pres / temp0
    qud = uwnd * (qvapor * rhodd + rhod * qvapord) + rhod * qvapor * uwndd
    qu = rhod * qvapor * uwnd
    qvd = vwnd * (qvapor * rhodd + rhod * qvapord) + rhod * qvapor * vwndd
    qv = rhod * qvapor * vwnd
    qwd = wwnd * (qvapor * rhodd + rhod * qvapord) + rhod * qvapor * wwndd
    qw = rhod * qvapor * wwnd
    c_thetad = 0.0_8
    pm2td = 0.0_8
    dtheta_m2d = 0.0_8
    temp_cd = 0.0_8
    theta_cd = 0.0_8
    divqd = 0.0_8
    dtheta_dz2d = 0.0_8
    c_qd = 0.0_8
    DO i = 1, num_icell
      IF (cell_type(i) .EQ. 0) THEN
        uwnd1d = uwnd(2:vlevel, i)
        vwnd1d = vwnd(2:vlevel, i)
        wwnd1d = wwnd(2:vlevel, i)
        pres1dd = presd(2:vlevel, i) / 1.0D02
        pres1d = pres(2:vlevel, i) / 1.0D02
        theta1dd = thetad(2:vlevel, i)
        theta1d = theta(2:vlevel, i)
        temp1dd = tempd(2:vlevel, i)
        temp1d = temp(2:vlevel, i)
        qvapor1dd = qvapord(2:vlevel, i)
        qvapor1d = qvapor(2:vlevel, i)
        gph1d = gph(2:vlevel, i)
        rhod1dd = rhodd(2:vlevel, i)
        rhod1d = rhod(2:vlevel, i)
        gph1dm = (gph1d(2:vlevel1d) + gph1d(1:vlevel1d - 1)) / 2.0D0
        d_3m = (gph1dm(vlevel1d - 1) - gph1dm(1)) / size_3m
        DO kgph = 1, size_3m
          gph1dm2(kgph) = gph1dm(1) + d_3m * (kgph - 1)
        END DO
        c_thetad(1) = 0.0_8
        c_theta(1) = 0.0D0
        c_qd(1) = 0.0_8
        c_q(1) = 0.0D0
        tlcld = temp1dd
        tlcl = temp1d
        DO k = 1, vlevel1d
          DO keps = 1, 5
            arg1d = 6.1094D0 * qvapor1dd(k)
            arg1 = (epsw_r + qvapor1d(k)) * 6.1094D0
            arg2d = 6.1094D0 * qvapor1dd(k)
            arg2 = (epsw_r + qvapor1d(k)) * 6.1094D0
            temp1 = DLOG(tlcl(k))
            temp2 = (a + tlcl(k)) / k_d
            temp3 = DLOG(qvapor1d(k)) + DLOG(pres1d(k)) - DLOG(temp1d(k)) /&
  &           k_d - DLOG(arg1) - 17.625D0
            ftsd = (temp1 / k_d + temp2 / tlcl(k) + temp3) * tlcld(k) + tlcl(k) * (&
  &           qvapor1dd(k) / qvapor1d(k) + pres1dd(k) / pres1d(k) - temp1dd(k) / (&
  &           k_d * temp1d(k)) - arg1d / arg1) + a * (qvapor1dd(k) / qvapor1d(k) +&
  &           pres1dd(k) / pres1d(k) - temp1dd(k) / (k_d * temp1d(k)) - arg2d / arg2)
            fts = tk * 17.625D0 + temp2 * temp1 + tlcl(k) * temp3 + a * (DLOG(&
  &           qvapor1d(k)) + DLOG(pres1d(k)) - DLOG(temp1d(k)) / k_d - DLOG(arg2))
            temp2 = (a + tlcl(k)) / (k_d * tlcl(k))
            temp3 = 6.1094D0 * (epsw_r + qvapor1d(k))
            dftsd = (1.0 / (k_d * tlcl(k)) + (1.0 - temp2 * k_d) / (k_d * tlcl(k))) *&
  &           tlcld(k) + (1.0 / qvapor1d(k) - 6.1094D0 / temp3) * qvapor1dd(k) + &
  &           pres1dd(k) / pres1d(k) - temp1dd(k) / (k_d * temp1d(k))
            dfts = DLOG(tlcl(k)) / k_d + temp2 + DLOG(qvapor1d(k)) + DLOG(&
  &           pres1d(k)) - DLOG(temp1d(k)) / k_d - DLOG(temp3) - 17.625D0
            tlcl1d = tlcld(k) - (ftsd - fts * dftsd / dfts) / dfts
            tlcl1 = tlcl(k) - fts / dfts
            tlcld(k) = tlcl1d
            tlcl(k) = tlcl1
          END DO
        END DO
        temp4 = qvapor1d / (cp * tlcl)
        arg10d(:) = lv * (qvapor1dd - temp4 * cp * tlcld) / (cp * tlcl)
        arg10(:) = lv * temp4
        temp5 = DEXP(arg10(:))
        theta_ed = temp5 * theta1dd + theta1d * DEXP(arg10(:)) * arg10d(:)
        theta_e = theta1d * temp5
        k = 1
        k_ref = vlevel / 2
        ! The first activation function
        arg1d = 2.0D0 * (theta_ed(1) - theta_ed(k_ref))
        arg1 = (theta_e(1) - theta_e(k_ref) - 1.0D0) * 2.0D0
        act_dthetaed = (1.0 - TANH(arg1)**2) * arg1d / 2.0D0
        act_dthetae = (TANH(arg1) + 1.0D0) / 2.0D0
        qvapor1dmeand = SUM(qvapor1dd(1:3)) / 3.0D0
        qvapor1dmean = SUM(qvapor1d(1:3)) / 3.0D0
        pres1dmeand = SUM(pres1dd(1:3)) / 3.0D0
        pres1dmean = SUM(pres1d(1:3)) / 3.0D0
        temp1dmeand = SUM(temp1dd(1:3)) / 3.0D0
        temp1dmean = SUM(temp1d(1:3)) / 3.0D0
        gph1dmean = SUM(gph1d(1:3)) / 3.0D0
        tbd = temp1dmeand
        tb = temp1dmean
        DO keps = 1, 5
          temp3 = DLOG(tb)
          temp1 = DLOG(qvapor1dmean) + DLOG(pres1dmean) - r_k_d * DLOG(&
  &         temp1dmean) - DLOG(6.1094D0 * (epsw_r + qvapor1dmean)) - 1.7625D01
          ftsd = (r_k_d * (temp3 + (a + tb) / tb) + temp1) * tbd + tb * ((1.0 /&
  &         qvapor1dmean - 1.0 / (epsw_r + qvapor1dmean)) * qvapor1dmeand +&
  &         pres1dmeand / pres1dmean - r_k_d * temp1dmeand / temp1dmean) + a * ((1.0&
  &         / qvapor1dmean - 1.0 / (epsw_r + qvapor1dmean)) * qvapor1dmeand +&
  &         pres1dmeand / pres1dmean - r_k_d * temp1dmeand / temp1dmean)
          fts = tk * 1.7625D01 + r_k_d * ((a + tb) * temp3) + tb * temp1 + a * (DLOG(&
  &         qvapor1dmean) + DLOG(pres1dmean) - r_k_d * DLOG(temp1dmean) - DLOG(&
  &         6.1094D0 * (epsw_r + qvapor1dmean)))
          temp2 = (a + tb) / tb
          dftsd = (r_k_d / tb + r_k_d * (1.0 - temp2) / tb) * tbd + (1.0 / qvapor1dmean -&
  &         1.0 / (epsw_r + qvapor1dmean)) * qvapor1dmeand + pres1dmeand /&
  &         pres1dmean - r_k_d * temp1dmeand / temp1dmean
          dfts = r_k_d * DLOG(tb) + r_k_d * temp2 + DLOG(qvapor1dmean) + DLOG(&
  &         pres1dmean) - r_k_d * DLOG(temp1dmean) - DLOG(6.1094D0 * (epsw_r +&
  &         qvapor1dmean)) - 1.7625D01
          tb1d = tbd - (ftsd - fts * dftsd / dfts) / dfts
          tb1 = tb - fts / dfts
          tbd = tb1d
          tb = tb1
        END DO
        hbd = cp * (temp1dmeand - tbd) / g
        hb = (temp1dmean - tb) / g * cp + gph1dmean
        WHERE (gph1d - hb .GE. 0.)
          dabs0 = gph1d - hb
        ELSEWHERE
          dabs0 = -(gph1d - hb)
        END WHERE
        ! Cloud base found
        k_bot = MINLOC(dabs0, 1)
        q_cd = qvapor1dd
        q_c = qvapor1d
        theta_cd(1:k_bot) = theta1dd(1)
        theta_c(1:k_bot) = theta1d(1)
        temp_cd(k_bot) = tbd
        temp_c(k_bot) = tb
        DO k = k_bot, vlevel1d - 1
          tempt1d = temp_cd(k)
          tempt1 = temp_c(k)
          IF (tempt1 .LE. 3.011D01) THEN
            gamma_m1 = -gamma_d
            gamma_m2 = -gamma_d
            q_cd(k) = 0.0_8
            q_c(k) = 0.0D0
          ELSE
            temp2 = (tempt1 - tk) / (tempt1 - 3.011D01)
            arg11d = 1.7625D01 * (1.0 - temp2) * tempt1d / (tempt1 - 3.011D01)
            arg11 = 1.7625D01 * temp2
            est1d = 6.1094D0 * EXP(arg11) * arg11d
            est1 = 6.1094D0 * EXP(arg11)
            temp2 = est1 / (pres1d(k) - est1)
            q_cd(k) = epsw_r * (est1d - temp2 * (pres1dd(k) - est1d)) / (pres1d(k) -&
  &           est1)
            q_c(k) = epsw_r * temp2
            temp2 = tempt1**2.0D0
            temp6 = cp * r_d * pres1d(k)
            temp7 = temp6 * temp2
            temp8 = lv**2.0D0 * epsw_r**2.0D0
            temp9 = temp8 * est1 / temp7 + 1.0D0
            temp10 = pres1d(k) * r_d * tempt1
            temp11 = est1 / temp10
            temp12 = (lv * epsw_r * temp11 + 1.0D0) / temp9
            gamma_m1d = -(gamma_d * (lv * epsw_r * (est1d - temp11 * (r_d * tempt1 *&
  &           pres1dd(k) + pres1d(k) * r_d * tempt1d)) / temp10 - temp12 * temp8 * (&
  &           est1d - est1 * (temp2 * cp * r_d * pres1dd(k) + temp6 * 2.0D0 * tempt1 *&
  &           tempt1d) / temp7) / temp7) / temp9)
            gamma_m1 = -(gamma_d * temp12)
            tempt2d = tempt1d + (gph1d(k + 1) - gph1d(k)) * gamma_m1d
            tempt2 = tempt1 + gamma_m1 * (gph1d(k + 1) - gph1d(k))
            IF (tempt2 .GT. 3.011D01) THEN
              temp12 = (tempt2 - tk) / (tempt2 - 3.011D01)
              arg11d = 1.7625D01 * (1.0 - temp12) * tempt2d / (tempt2 - 3.011D01)
              arg11 = 1.7625D01 * temp12
              est2d = 6.1094D0 * EXP(arg11) * arg11d
              est2 = 6.1094D0 * EXP(arg11)
              temp12 = tempt2**2.0D0
              temp11 = cp * r_d * pres1d(k + 1)
              temp10 = temp11 * temp12
              temp9 = lv**2.0D0 * epsw_r**2.0D0
              temp8 = temp9 * est2 / temp10 + 1.0D0
              temp7 = pres1d(k + 1) * r_d * tempt2
              temp6 = est2 / temp7
              temp2 = (lv * epsw_r * temp6 + 1.0D0) / temp8
              gamma_m2d = -(gamma_d * (lv * epsw_r * (est2d - temp6 * (r_d * tempt2 *&
  &             pres1dd(k + 1) + pres1d(k + 1) * r_d * tempt2d)) / temp7 - temp2 * temp9 * (&
  &             est2d - est2 * (temp12 * cp * r_d * pres1dd(k + 1) + temp11 * 2.0D0 * tempt2&
  &             * tempt2d) / temp10) / temp10) / temp8)
              gamma_m2 = -(gamma_d * temp2)
            ELSE
              gamma_m2 = -gamma_d
              gamma_m2d = 0.0_8
            END IF
            temp_cd(k + 1) = tempt1d + (gph1d(k + 1) - gph1d(k)) * (gamma_m1d +&
  &           gamma_m2d) / 2.0D0
            temp_c(k + 1) = tempt1 + (gamma_m1 + gamma_m2) * (gph1d(k + 1) - gph1d(k&
  &           )) / 2.0D0
            temp3 = 1.0D03 / pres1d(k + 1)
            pwx10d = -(temp3 * pres1dd(k + 1) / pres1d(k + 1))
            pwx10 = temp3
            IF (pwx10 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT(k_d))&
  &         ) THEN
              pwr10d = 0.D0
            ELSE
              pwr10d = k_d * pwx10**(k_d - 1) * pwx10d
            END IF
            pwr10 = pwx10**k_d
            theta_cd(k + 1) = pwr10 * temp_cd(k + 1) + temp_c(k + 1) * pwr10d
            theta_c(k + 1) = temp_c(k + 1) * pwr10
          END IF
        END DO
        dthetad = theta_cd - theta1dd
        dtheta = theta_c - theta1d
        dtheta_dzd = (dthetad(2:vlevel1d) - dthetad(1:vlevel1d - 1)) / (gph1d(2:&
  &       vlevel1d) - gph1d(1:vlevel1d - 1))
        dtheta_dz = (dtheta(2:vlevel1d) - dtheta(1:vlevel1d - 1)) / (gph1d(2:&
  &       vlevel1d) - gph1d(1:vlevel1d - 1))
        dtheta_md = (dthetad(2:vlevel1d) + dthetad(1:vlevel1d - 1)) / 2.0D0
        dtheta_m = (dtheta(2:vlevel1d) + dtheta(1:vlevel1d - 1)) / 2.0D0
        pmd = (pres1dd(2:vlevel1d) / pres1d(2:vlevel1d) + pres1dd(1:vlevel1d - 1&
  &       ) / pres1d(1:vlevel1d - 1)) / 2.0D0
        pm = (DLOG(pres1d(2:vlevel1d)) + DLOG(pres1d(1:vlevel1d - 1))) / 2.0D0
        ! DO kgph = 1, size_3m
        !     gph1dm2(kgph) = gph1dm(1) + 3.0D0*(kgph-1)
        ! END DO
        CALL INTERP1D_D(gph1dm, dtheta_m, dtheta_md, vlevel1d2, gph1dm2, &
  &               dtheta_m2, dtheta_m2d)
        CALL INTERP1D_D(gph1dm, dtheta_dz, dtheta_dzd, vlevel1d2, gph1dm2&
  &               , dtheta_dz2, dtheta_dz2d)
        CALL INTERP1D_D(gph1dm, pm, pmd, vlevel1d2, gph1dm2, pm2t, pm2td)
        pm2d = EXP(pm2t) * pm2td
        pm2 = EXP(pm2t)
        act_p500_ctd = -((1.0 - TANH((5.0D02 - pm2) / 8.0D01)**2) * pm2d / (2.0D0 *&
  &       8.0D01))
        act_p500_ct = (TANH((5.0D02 - pm2) / 8.0D01) + 1.0D0) / 2.0D0
        act_p500_lfcd = (1.0 - TANH((pm2 - 5.0D02) / 8.0D01)**2) * pm2d / (2.0D0 *&
  &       8.0D01)
        act_p500_lfc = (TANH((-5.0D02 + pm2) / 8.0D01) + 1.0D0) / 2.0D0
        act_dthz_ctd = -((1.0 - TANH(3.0D04 * dtheta_dz2)**2) * 3.0D04 *&
  &       dtheta_dz2d / 2.0D0)
        act_dthz_ct = (-TANH(dtheta_dz2 * 3.0D04) + 1.0D0) / 2.0D0
        temp13 = 1.0 / (5.0D03 * dtheta_m2**4.0D0 + 1.0D0)
        act_dth_ctd = -(temp13 * 5.0D03 * 4.0D0 * dtheta_m2**3.0D0 * dtheta_m2d / (&
  &       5.0D03 * dtheta_m2**4.0D0 + 1.0D0))
        act_dth_ct = temp13
        act_dthz_lfcd = (1.0 - TANH(1.0D04 * dtheta_dz2)**2) * 1.0D04 *&
  &       dtheta_dz2d / 2.0D0
        act_dthz_lfc = (TANH(dtheta_dz2 * 1.0D04) + 1.0D0) / 2.0D0
        temp13 = 1.0 / (5.0D03 * dtheta_m2**4.0D0 + 1.0D0)
        act_dth_lfcd = -(temp13 * 5.0D03 * 4.0D0 * dtheta_m2**3.0D0 * dtheta_m2d / (&
  &       5.0D03 * dtheta_m2**4.0D0 + 1.0D0))
        act_dth_lfc = temp13
        act_ctd = act_dth_ct * (act_dthz_ct * act_p500_ctd + act_p500_ct *&
  &       act_dthz_ctd) + act_p500_ct * act_dthz_ct * act_dth_ctd
        act_ct = act_p500_ct * act_dthz_ct * act_dth_ct
        arg11d = -(1.0D01 * SUM(act_ctd))
        arg11 = -(1.0D01 * SUM(act_ct))
        temp3 = 2.0D0 / (EXP(arg11) + 1.0D0)
        act_sum_ctd = -(temp3 * EXP(arg11) * arg11d / (EXP(arg11) + 1.0D0))
        act_sum_ct = temp3 - 1.0D0
        act_lfcd = act_dth_lfc * (act_dthz_lfc * act_p500_lfcd + act_p500_lfc *&
  &       act_dthz_lfcd) + act_p500_lfc * act_dthz_lfc * act_dth_lfcd
        act_lfc = act_p500_lfc * act_dthz_lfc * act_dth_lfc
        dgphm = gph1dm2(2:size_3m) - gph1dm2(1:size_3m - 1)
        arg12d(:) = dgphm * (gph1dm2(1:size_3m - 1) * act_ctd(1:size_3m - 1) +&
  &       gph1dm2(2:size_3m) * act_ctd(2:size_3m))
        arg12(:) = (act_ct(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_ct(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm
        arg20d(:) = dgphm * (act_ctd(1:size_3m - 1) + act_ctd(2:size_3m))
        arg20(:) = (act_ct(1:size_3m - 1) + act_ct(2:size_3m)) * dgphm
        temp12 = SUM(arg20(:))
        temp11 = SUM(arg12(:))
        temp10 = act_sum_ct * temp11 / temp12
        httd = (temp11 * act_sum_ctd + act_sum_ct * SUM(arg12d(:)) - temp10 * SUM(&
  &       arg20d(:))) / temp12
        htt = temp10
        arg12d(:) = dgphm * (gph1dm2(1:size_3m - 1) * act_lfcd(1:size_3m - 1) +&
  &       gph1dm2(2:size_3m) * act_lfcd(2:size_3m))
        arg12(:) = (act_lfc(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_lfc(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm
        arg20d(:) = dgphm * (act_lfcd(1:size_3m - 1) + act_lfcd(2:size_3m))
        arg20(:) = (act_lfc(1:size_3m - 1) + act_lfc(2:size_3m)) * dgphm
        temp12 = SUM(arg20(:))
        temp11 = SUM(arg12(:))
        temp10 = act_sum_ct * temp11 / temp12
        lfctd = (temp11 * act_sum_ctd + act_sum_ct * SUM(arg12d(:)) - temp10 * SUM(&
  &       arg20d(:))) / temp12
        lfct = temp10
        temp14 = 1.0 / ((gph1dm2 - htt)**4.0D0 / 1.0D08 + 1.0D0)
        act_ptd = temp14 * 4.0D0 * (gph1dm2 - htt)**3.0D0 * httd / (((gph1dm2 - htt)**&
  &       4.0D0 / 1.0D08 + 1.0D0) * 1.0D08)
        act_pt = temp14
        temp14 = 1.0 / ((gph1dm2 - lfct)**4.0D0 / 1.0D08 + 1.0D0)
        act_lfc2d = temp14 * 4.0D0 * (gph1dm2 - lfct)**3.0D0 * lfctd / (((gph1dm2 -&
  &       lfct)**4.0D0 / 1.0D08 + 1.0D0) * 1.0D08)
        act_lfc2 = temp14
        arg12d(:) = dgphm * (pm2(1:size_3m - 1) * act_ptd(1:size_3m - 1) + act_pt(1:&
  &       size_3m - 1) * pm2d(1:size_3m - 1) + pm2(2:size_3m) * act_ptd(2:size_3m) +&
  &       act_pt(2:size_3m) * pm2d(2:size_3m))
        arg12(:) = (act_pt(1:size_3m - 1) * pm2(1:size_3m - 1) + act_pt(2:size_3m)&
                   &       * pm2(2:size_3m)) * dgphm
        arg20d(:) = dgphm * (act_ptd(1:size_3m - 1) + act_ptd(2:size_3m))
        arg20(:) = (act_pt(1:size_3m - 1) + act_pt(2:size_3m)) * dgphm
        temp12 = SUM(arg20(:))
        temp11 = SUM(arg12(:)) / temp12
        ptd = (SUM(arg12d(:)) - temp11 * SUM(arg20d(:))) / temp12
        pt = temp11
        arg12d(:) = dgphm * (gph1dm2(1:size_3m - 1) * act_ptd(1:size_3m - 1) +&
  &       gph1dm2(2:size_3m) * act_ptd(2:size_3m))
        arg12(:) = (act_pt(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_pt(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm
        arg20d(:) = dgphm * (act_ptd(1:size_3m - 1) + act_ptd(2:size_3m))
        arg20(:) = (act_pt(1:size_3m - 1) + act_pt(2:size_3m)) * dgphm
        temp12 = SUM(arg20(:))
        temp11 = SUM(arg12(:)) / temp12
        htd = (SUM(arg12d(:)) - temp11 * SUM(arg20d(:))) / temp12
        ht = temp11
        arg12d(:) = dgphm * (gph1dm2(1:size_3m - 1) * act_lfc2d(1:size_3m - 1) +&
  &       gph1dm2(2:size_3m) * act_lfc2d(2:size_3m))
        arg12(:) = (act_lfc2(1:size_3m - 1) * gph1dm2(1:size_3m - 1) + act_lfc2(2:&
  &       size_3m) * gph1dm2(2:size_3m)) * dgphm
        arg20d(:) = dgphm * (act_lfc2d(1:size_3m - 1) + act_lfc2d(2:size_3m))
        arg20(:) = (act_lfc2(1:size_3m - 1) + act_lfc2(2:size_3m)) * dgphm
        temp12 = SUM(arg20(:))
        temp11 = SUM(arg12(:)) / temp12
        lfcd = (SUM(arg12d(:)) - temp11 * SUM(arg20d(:))) / temp12
        lfc = temp11
        arg1d = (htd - lfcd) / 5.0D02
        arg1 = (ht - lfc - 3.0D03) / 5.0D02
        act_dzd = (1.0 - TANH(arg1)**2) * arg1d / 2.0D0
        act_dz = (TANH(arg1) + 1.0D0) / 2.0D0
        ! Third activation function
        act_p500d = -((1.0 - TANH((5.0D02 - pt) / 5.0D01)**2) * ptd / (2.0D0 * 5.0D01)&
  &       )
        act_p500 = (TANH((5.0D02 - pt) / 5.0D01) + 1.0D0) / 2.0D0
        act_cind = (1.0 - TANH((lfc - gph1d) / 5.0D02)**2) * lfcd / (2.0D0 * 5.0D02)
        act_cin = (TANH((lfc - gph1d) / 5.0D02) + 1.0D0) / 2.0D0
        act_dth_cind = dtheta * act_cind + act_cin * dthetad
        act_dth_cin = act_cin * dtheta
        arg13d(:) = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * (act_dth_cind(&
  &       2:vlevel1d) + act_dth_cind(1:vlevel1d - 1))
        arg13(:) = (act_dth_cin(2:vlevel1d) + act_dth_cin(1:vlevel1d - 1)) * (&
  &       gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1))
        cind = SUM(arg13d(:)) / 2.0D0
        cin = SUM(arg13(:)) / 2.0D0
        temp4 = (2.0D0 * gph1d - ht - lfc) / (ht - lfc)
        z_ud = (-htd - lfcd - temp4 * (htd - lfcd)) / (ht - lfc)
        z_u = temp4
        temp4 = 1.0 / (z_u**8.0D0 + 1.0D0)
        act_zud = -(temp4 * 8.0D0 * z_u**7.0D0 * z_ud / (z_u**8.0D0 + 1.0D0))
        act_zu = temp4
        act_dth_caped = dtheta * act_zud + act_zu * dthetad
        act_dth_cape = act_zu * dtheta
        arg13d(:) = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * (act_dth_caped&
  &       (2:vlevel1d) + act_dth_caped(1:vlevel1d - 1))
        arg13(:) = (act_dth_cape(2:vlevel1d) + act_dth_cape(1:vlevel1d - 1)) * (&
  &       gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1))
        caped = SUM(arg13d(:)) / 2.0D0
        cape = SUM(arg13(:)) / 2.0D0
        ! Fourth activation function
        arg1d = (caped + cind) / 1.0D03
        arg1 = (cape + 1.0D0 * cin) / 1.0D03 - 2.5D0
        act_caped = (1.0 - TANH(arg1)**2) * arg1d / 2.0D0
        act_cape = (TANH(arg1) + 1.0D0) / 2.0D0
        temp4 = (2.0D0 * gph1d - ht - hb) / (ht - hb)
        z_u2d = (-htd - hbd - temp4 * (htd - hbd)) / (ht - hb)
        z_u2 = temp4
        temp4 = 1.0 / (z_u2**8.0D0 + 1.0D0)
        act_zu2d = -(temp4 * 8.0D0 * z_u2**7.0D0 * z_u2d / (z_u2**8.0D0 + 1.0D0))
        act_zu2 = temp4
        sum_act_zu2d = SUM(act_zu2d)
        sum_act_zu2 = SUM(act_zu2)
        arg10d(:) = 2.0D0 * act_zu2 * act_zu2d
        arg10(:) = act_zu2**2.0D0
        sum_act_zu2_p2d = SUM(arg10d(:))
        sum_act_zu2_p2 = SUM(arg10(:))
        act_dth_dd = dtheta * act_zu2d + act_zu2 * dthetad
        act_dth_d = act_zu2 * dtheta
        temp12 = SUM(act_dth_d) / sum_act_zu2
        dth_md = (SUM(act_dth_dd) - temp12 * sum_act_zu2d) / sum_act_zu2
        dth_m = temp12
        act_dth_md = act_zu2 * dth_md + dth_m * act_zu2d
        act_dth_m = dth_m * act_zu2
        arg10d(:) = 2.0D0 * (act_dth_d - act_dth_m) * (act_dth_dd - act_dth_md)
        arg10(:) = (act_dth_d - act_dth_m)**2.0D0
        temp12 = SUM(arg10(:)) / sum_act_zu2_p2
        arg2d = (SUM(arg10d(:)) - temp12 * sum_act_zu2_p2d) / sum_act_zu2_p2
        arg2 = temp12
        temp12 = SQRT(arg2)
        IF (arg2 .EQ. 0.0) THEN
          dth_stdd = 0.0_8
        ELSE
          dth_stdd = arg2d / (2.0 * temp12)
        END IF
        dth_std = temp12
        max_dthetad = dth_md + 1.5D0 * dth_stdd
        max_dtheta = dth_m + 1.5D0 * dth_std
        temp3 = 5.0D0 / (EXP(-max_dtheta + 2.5D0) + 1.0D0)
        dd = temp3 * EXP(2.5D0 - max_dtheta) * max_dthetad / (EXP(2.5D0 - max_dtheta&
  &       ) + 1.0D0)
        d = temp3
        arg10(:) = gph1d - gph1d(1)
        result1 = SQRT(arg10(:))
        temp12 = SQRT(ht)
        IF (ht .EQ. 0.0) THEN
          result2d = 0.0_8
        ELSE
          result2d = htd / (2.0 * temp12)
        END IF
        result2 = temp12
        temp4 = 4.0D0 * result1 / result2
        arg21d(:) = temp4 * result2d / result2
        arg21(:) = -temp4
        temp4 = EXP(arg21(:))
        theta_downd = theta1dd - d * EXP(arg21(:)) * arg21d(:) - temp4 * dd
        theta_down = theta1d - temp4 * d
        arg10(:) = gph1d - gph1d(1)
        result1 = SQRT(arg10(:))
        temp12 = SQRT(ht)
        IF (ht .EQ. 0.0) THEN
          result2d = 0.0_8
        ELSE
          result2d = htd / (2.0 * temp12)
        END IF
        result2 = temp12
        temp4 = 5.0D0 * result1 / result2
        beta_thetad = EXP(-temp4) * temp4 * result2d / result2
        beta_theta = EXP(-temp4)
        theta_cond = (theta_down - theta_c) * beta_thetad + beta_theta *&
  &       theta_downd + (1.0D0 - beta_theta) * theta_cd
        theta_con = beta_theta * theta_down + (1.0D0 - beta_theta) * theta_c
        q_contd = q_cd - qvapor1dd
        q_cont = q_c - qvapor1d
        q_cond = act_zu2 * q_contd + q_cont * act_zu2d
        q_con = q_cont * act_zu2
        i_e = cell_stcl(6, i)
        i_w = cell_stcl(4, i)
        i_n = cell_stcl(8, i)
        i_s = cell_stcl(2, i)
        qu_cd = qud(:, i)
        qu_c = qu(:, i)
        qu_ed = qud(:, i_e)
        qu_e = qu(:, i_e)
        qu_wd = qud(:, i_w)
        qu_w = qu(:, i_w)
        qv_c = qv(:, i)
        qv_cd = qvd(:, i)
        qv_c = qv(:, i)
        qv_nd = qvd(:, i_n)
        qv_n = qv(:, i_n)
        qv_sd = qvd(:, i_s)
        qv_s = qv(:, i_s)
        qw_cd = qwd(:, i)
        qw_c = qw(:, i)
        CALL DIVERGENCE_D(qu_c, qu_cd, qu_w, qu_wd, qu_e, qu_ed, qv_c, &
  &                 qv_cd, qv_s, qv_sd, qv_n, qv_nd, qw_c, qw_cd, sigma, &
  &                 ztop, topo(i), topo(i_w), topo(i_e), topo(i_s), topo(&
  &                 i_n), cell_dist(4, i), cell_dist(2, i), vlevel, divq, &
  &                 divqd)
        act_htd = (1.0 - TANH((ht - gph1d) / 1.0D02)**2) * htd / (2.0D0 * 1.0D02)
        act_ht = (TANH((-gph1d + ht) / 1.0D02) + 1.0D0) / 2.0D0
        arg14d(:) = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * (act_ht(1:&
  &       vlevel1d - 1) * divqd(2:vlevel - 1) + divq(2:vlevel - 1) * act_htd(1:&
  &       vlevel1d - 1) + act_ht(2:vlevel1d) * divqd(3:vlevel) + divq(3:vlevel) *&
  &       act_htd(2:vlevel1d))
        arg14(:) = (divq(2:vlevel - 1) * act_ht(1:vlevel1d - 1) + divq(3:vlevel) *&
  &       act_ht(2:vlevel1d)) * (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1))
        ird = -(SUM(arg14d(:)) / 2.0D0)
        ir = -(SUM(arg14(:)) / 2.0D0)
        arg15d(:) = 1.7625D01 * (1.0 - (temp1d - tk) / (temp1d - 3.011D01)) * temp1dd /&
  &       (temp1d - 3.011D01)
        arg15(:) = 1.7625D01 * (temp1d - tk) / (temp1d - 3.011D01)
        psatd = 6.1094D0 * EXP(arg15(:)) * arg15d(:)
        psat = 6.1094D0 * EXP(arg15(:))
        qsatd = epsw_r * (psatd - psat * (pres1dd - psatd) / (pres1d - psat)) / (pres1d -&
  &       psat)
        qsat = psat / (pres1d - psat) * epsw_r
        q1d_sumd = SUM(act_ht * qvapor1dd + qvapor1d * act_htd)
        q1d_sum = SUM(qvapor1d * act_ht)
        qsat_sumd = SUM(act_ht * qsatd + qsat * act_htd)
        qsat_sum = SUM(qsat * act_ht)
        rhd = (q1d_sumd - q1d_sum * qsat_sumd / qsat_sum) / qsat_sum
        rh = q1d_sum / qsat_sum
        act_rhd = (1.0 - TANH(4.0D01 * (rh - 6.8D-1))**2) * 4.0D01 * rhd / 2.0D0
        act_rh = (TANH((rh - 6.8D-1) * 4.0D01) + 1.0D0) / 2.0D0
        b_paramd = 5.0D-1 * ((1.0D0 - rh) * act_rhd - act_rh * rhd) - act_rhd
        b_param = act_rh * (1.0D0 - rh) * 5.0D-1 + (1.0D0 - act_rh)
        act_ht_md = (act_htd(2:vlevel1d) + act_htd(1:vlevel1d - 1)) / 2.0D0
        act_ht_m = (act_ht(2:vlevel1d) + act_ht(1:vlevel1d - 1)) / 2.0D0
        d_theta_cond = theta_cond - theta1dd
        d_theta_con = theta_con - theta1d
        d_theta_con_md = (d_theta_cond(2:vlevel1d) + d_theta_cond(1:vlevel1d&
  &       - 1)) / 2.0D0
        d_theta_con_m = (d_theta_con(2:vlevel1d) + d_theta_con(1:vlevel1d - 1)&
  &       ) / 2.0D0
        q_con_md = (q_cond(2:vlevel1d) + q_cond(1:vlevel1d - 1)) / 2.0D0
        q_con_m = (q_con(2:vlevel1d) + q_con(1:vlevel1d - 1)) / 2.0D0
        arg1d = 2.0D0 * 1.0D06 * ird
        arg1 = (ir * 1.0D06 - 1.5D0) * 2.0D0
        act_ird = (1.0 - TANH(arg1)**2) * arg1d / 2.0D0
        act_ir = (TANH(arg1) + 1.0D0) / 2.0D0
        temp12 = act_ir * act_dthetae * act_dz * act_p500
        c_stard = act_cape * ir * (act_dz * act_p500 * (act_dthetae * act_ird + act_ir&
  &       * act_dthetaed) + act_ir * act_dthetae * (act_p500 * act_dzd + act_dz *&
  &       act_p500d)) + temp12 * (ir * act_caped + act_cape * ird)
        c_star = temp12 * (act_cape * ir)
        d_c_stard = c_star * b_paramd + b_param * c_stard
        d_c_star = b_param * c_star
        precipd(i) = c_stard - d_c_stard
        precip(i) = c_star - d_c_star
        arg13d(:) = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * (d_theta_con_m&
                                                                  &       * act_ht_md + act_ht_m * d_theta_con_md)
        arg13(:) = act_ht_m * d_theta_con_m * (gph1d(2:vlevel1d) - gph1d(1:&
  &       vlevel1d - 1))
        pwx11d = -(1.0D03 * pres1dd / pres1d**2)
        pwx11 = 1.0D03 / pres1d
        WHERE (pwx11 .LE. 0.0 .AND. (k_d .EQ. 0.0 .OR. k_d .NE. INT(k_d))&
  &     )
          pwr11d = 0.D0
        ELSEWHERE
          pwr11d = k_d * pwx11**(k_d - 1) * pwx11d
        END WHERE
        pwr11 = pwx11**k_d
        temp12 = cp * SUM(arg13(:))
        temp4 = (c_star - d_c_star) * pwr11 * act_ht * d_theta_con / temp12
        c_thetad(2:vlevel) = lv * (act_ht * d_theta_con * (pwr11 * (c_stard -&
  &       d_c_stard) + (c_star - d_c_star) * pwr11d) + (c_star - d_c_star) * pwr11 * (&
  &       d_theta_con * act_htd + act_ht * d_theta_cond) - temp4 * cp * SUM(arg13d(:))&
  &       ) / temp12
        c_theta(2:vlevel) = lv * temp4
        arg13d(:) = (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)) * (q_con_m *&
  &       act_ht_md + act_ht_m * q_con_md)
        arg13(:) = act_ht_m * q_con_m * (gph1d(2:vlevel1d) - gph1d(1:vlevel1d - 1)&
  &       )
        temp12 = SUM(arg13(:))
        temp4 = d_c_star * act_ht * q_con / (temp12 * rhod1d)
        c_qd(2:vlevel) = (q_con * (act_ht * d_c_stard + d_c_star * act_htd) +&
  &       d_c_star * act_ht * q_cond - temp4 * (rhod1d * SUM(arg13d(:)) + temp12 *&
  &       rhod1dd)) / (temp12 * rhod1d)
        c_q(2:vlevel) = temp4
        ! precip(i) = act_Ir*act_dthetae*act_dz*act_P500*act_cape*(1.0D0 - b_param)*Ir*cu_dt
        theta1d_ed = thetad(:, i_e)
        theta1d_e = theta(:, i_e)
        theta1d_wd = thetad(:, i_w)
        theta1d_w = theta(:, i_w)
        theta1d_nd = thetad(:, i_n)
        theta1d_n = theta(:, i_n)
        theta1d_sd = thetad(:, i_s)
        theta1d_s = theta(:, i_s)
        theta1d_cd = thetad(:, i)
        theta1d_c = theta(:, i)
        uwnd1d_cd = uwndd(:, i)
        uwnd1d_c = uwnd(:, i)
        vwnd1d_cd = vwndd(:, i)
        vwnd1d_c = vwnd(:, i)
        wwnd1d_cd = wwndd(:, i)
        wwnd1d_c = wwnd(:, i)
        CALL TENDENCY_D(uwnd1d_c, uwnd1d_cd, vwnd1d_c, vwnd1d_cd, wwnd1d_c&
  &               , wwnd1d_cd, theta1d_c, theta1d_cd, theta1d_w, &
  &               theta1d_wd, theta1d_e, theta1d_ed, theta1d_s, theta1d_sd&
  &               , theta1d_n, theta1d_nd, vlevel, sigma, ztop, topo(i), &
  &               topo(i_w), topo(i_e), topo(i_s), topo(i_n), cell_dist(4&
  &               , i), cell_dist(2, i), c_theta, c_thetad, par_theta(:, i&
  &               ), par_thetad(:, i))
        q1d_ed = qvapord(:, i_e)
        q1d_e = qvapor(:, i_e)
        q1d_wd = qvapord(:, i_w)
        q1d_w = qvapor(:, i_w)
        q1d_nd = qvapord(:, i_n)
        q1d_n = qvapor(:, i_n)
        q1d_sd = qvapord(:, i_s)
        q1d_s = qvapor(:, i_s)
        q1d_cd = qvapord(:, i)
        q1d_c = qvapor(:, i)
        CALL TENDENCY_D(uwnd1d_c, uwnd1d_cd, vwnd1d_c, vwnd1d_cd, wwnd1d_c&
  &               , wwnd1d_cd, q1d_c, q1d_cd, q1d_w, q1d_wd, q1d_e, q1d_ed&
  &               , q1d_s, q1d_sd, q1d_n, q1d_nd, vlevel, sigma, ztop, &
  &               topo(i), topo(i_w), topo(i_e), topo(i_s), topo(i_n), &
  &               cell_dist(4, i), cell_dist(2, i), c_q, c_qd, par_q(:, i)&
  &               , par_qd(:, i))
      END IF
    END DO
  END SUBROUTINE CUMFWD_D

  !  Differentiation of divergence in forward (tangent) mode:
  !   variations   of useful results: divgc
  !   with respect to varying inputs: fv_c fv_n fv_s divgc fu_c fu_e
  !                fw fu_w
  SUBROUTINE DIVERGENCE_D(fu_c, fu_cd, fu_w, fu_wd, fu_e, fu_ed, fv_c, &
  & fv_cd, fv_s, fv_sd, fv_n, fv_nd, fw, fwd, sigma, ztop, topo_c, topo_w&
  & , topo_e, topo_s, topo_n, dist_we, dist_sn, vlevel, divgc, divgcd)
    IMPLICIT NONE
    REAL*8, DIMENSION(:), INTENT(IN) :: fu_c, fu_e, fu_w, fv_c, fv_n, fv_s&
  & , fw, sigma
    REAL*8, DIMENSION(:), INTENT(IN) :: fu_cd, fu_ed, fu_wd, fv_cd, fv_nd&
  & , fv_sd, fwd
    REAL*8, INTENT(IN) :: ztop, topo_c, topo_w, topo_e, topo_s, topo_n, &
  & dist_we, dist_sn
    INTEGER*4, INTENT(IN) :: vlevel
    REAL*8 :: h_0(vlevel - 2), h_n1(vlevel - 2), h_p1(vlevel - 2), par_fusigma(&
  & vlevel), par_fvsigma(vlevel), par_fwsigma(vlevel)
    REAL*8 :: par_fusigmad(vlevel), par_fvsigmad(vlevel), par_fwsigmad(&
  & vlevel)
    REAL*8, INTENT(INOUT) :: divgc(:)
    REAL*8, INTENT(INOUT) :: divgcd(:)
    REAL*8 :: rat, par_temp, par_sigmax, par_sigmay
    INTRINSIC SIZE
    rat = ztop / (ztop - topo_c)
    ! vlevel = SIZE(sigma)
    par_temp = 1 / (ztop - topo_c)**2.0D0
    par_sigmax = par_temp * (topo_e - topo_w) / 2.0D0 / dist_we
    par_sigmay = par_temp * (topo_n - topo_s) / 2.0D0 / dist_sn

    h_0 = (2.0D0 * sigma(2:vlevel - 1) - sigma(1:vlevel - 2) - sigma(3:vlevel)) / (&
  &   sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:vlevel&
  &   - 1))
    ! n represents negative
    h_n1 = (sigma(3:vlevel) - sigma(2:vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(2:&
  &   vlevel - 1)) / (sigma(3:vlevel) - sigma(1:vlevel - 2))
    ! p represents positive
    h_p1 = (sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:&
  &   vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(3:vlevel))
    par_fusigma(1) = 0.0D0
    par_fusigmad = 0.0_8
    par_fusigmad(2:vlevel - 1) = h_0 * fu_cd(2:vlevel - 1) + h_p1 * fu_cd(3:vlevel&
  &   ) + h_n1 * fu_cd(1:vlevel - 2)
    par_fusigma(2:vlevel - 1) = fu_c(2:vlevel - 1) * h_0 + fu_c(3:vlevel) * h_p1 +&
  &   fu_c(1:vlevel - 2) * h_n1
    par_fusigmad(vlevel) = 0.0_8
    par_fusigma(vlevel) = 0.0D0
    par_fvsigma(1) = 0.0D0
    par_fvsigmad = 0.0_8
    par_fvsigmad(2:vlevel - 1) = h_0 * fv_cd(2:vlevel - 1) + h_p1 * fv_cd(3:vlevel&
  &   ) + h_n1 * fv_cd(1:vlevel - 2)
    par_fvsigma(2:vlevel - 1) = fv_c(2:vlevel - 1) * h_0 + fv_c(3:vlevel) * h_p1 +&
  &   fv_c(1:vlevel - 2) * h_n1
    par_fvsigmad(vlevel) = 0.0_8
    par_fvsigma(vlevel) = 0.0D0
    par_fwsigma(1) = 0.0D0
    par_fwsigmad = 0.0_8
    par_fwsigmad(2:vlevel - 1) = h_0 * fwd(2:vlevel - 1) + h_p1 * fwd(3:vlevel) + &
  &   h_n1 * fwd(1:vlevel - 2)
    par_fwsigma(2:vlevel - 1) = fw(2:vlevel - 1) * h_0 + fw(3:vlevel) * h_p1 + fw(&
  &   1:vlevel - 2) * h_n1
    par_fwsigmad(vlevel) = 0.0_8
    par_fwsigma(vlevel) = 0.0D0
    divgcd(1) = (fu_ed(1) - fu_wd(1)) / (dist_we * 2.0D0) + (fv_nd(1) - fv_sd(1)) /&
  &   (dist_sn * 2.0D0)
    divgc(1) = (fu_e(1) - fu_w(1)) / dist_we / 2.0D0 + (fv_n(1) - fv_s(1)) / dist_sn&
  &   / 2.0D0
    divgcd(2:vlevel - 1) = (fu_ed(2:vlevel - 1) - fu_wd(2:vlevel - 1)) / (dist_we *&
  &   2.0D0) + (fv_nd(2:vlevel - 1) - fv_sd(2:vlevel - 1)) / (dist_sn * 2.0D0) - &
  &   par_sigmax * par_fusigmad(2:vlevel - 1) + rat * par_fwsigmad(2:vlevel - 1) -&
  &   par_sigmay * par_fvsigmad(2:vlevel - 1)
    divgc(2:vlevel - 1) = (fu_e(2:vlevel - 1) - fu_w(2:vlevel - 1)) / dist_we / 2.0D0 &
  &   + (fv_n(2:vlevel - 1) - fv_s(2:vlevel - 1)) / dist_sn / 2.0D0 - par_fusigma(2:&
  &   vlevel - 1) * par_sigmax - par_fvsigma(2:vlevel - 1) * par_sigmay + rat *&
  &   par_fwsigma(2:vlevel - 1)
    divgcd(vlevel) = (fu_ed(vlevel) - fu_wd(vlevel)) / (dist_we * 2.0D0) + (&
  &   fv_nd(vlevel) - fv_sd(vlevel)) / (dist_sn * 2.0D0)
    divgc(vlevel) = (fu_e(vlevel) - fu_w(vlevel)) / dist_we / 2.0D0 + (fv_n(&
  &   vlevel) - fv_s(vlevel)) / dist_sn / 2.0D0
  END SUBROUTINE DIVERGENCE_D

  !  Differentiation of tendency in forward (tangent) mode:
  !   variations   of useful results: ten
  !   with respect to varying inputs: y1 vwnd uwnd ten y_e righthand
  !                y_n y_s y_w wwnd
  SUBROUTINE TENDENCY_D(uwnd, uwndd, vwnd, vwndd, wwnd, wwndd, y1, y1d, &
  & y_w, y_wd, y_e, y_ed, y_s, y_sd, y_n, y_nd, vlevel, sigma, ztop, &
  & topo_c, topo_w, topo_e, topo_s, topo_n, dist_we, dist_sn, righthand, &
  & righthandd, ten, tend)
    IMPLICIT NONE
    REAL*8, DIMENSION(:), INTENT(IN) :: uwnd, vwnd, wwnd, y1, y_e, y_w, &
  & y_n, y_s, sigma
    REAL*8, DIMENSION(:), INTENT(IN) :: uwndd, vwndd, wwndd, y1d, y_ed, &
  & y_wd, y_nd, y_sd
    REAL*8, INTENT(IN) :: ztop, topo_c, topo_w, topo_e, topo_s, topo_n, &
  & dist_we, dist_sn
    REAL*8, INTENT(IN), OPTIONAL :: righthand(:)
    REAL*8, INTENT(IN), OPTIONAL :: righthandd(:)
    INTEGER*4, INTENT(IN) :: vlevel
    REAL*8 :: wwnd_s(vlevel), h_0(vlevel - 2), h_n1(vlevel - 2), h_p1(vlevel - 2&
  & ), par_ysigma(vlevel), par_temp, par_sigmax, par_sigmay
    REAL*8 :: wwnd_sd(vlevel), par_ysigmad(vlevel)
    REAL*8, INTENT(INOUT) :: ten(:)
    REAL*8, INTENT(INOUT) :: tend(:)
    INTRINSIC SIZE
    INTRINSIC PRESENT
    REAL*8, DIMENSION(vlevel - 2) :: temp
    REAL*8, DIMENSION(vlevel - 2) :: temp0
    REAL*8 :: temp1
    REAL*8 :: temp2

    wwnd_sd = ztop * wwndd / (ztop - topo_c)
    wwnd_s = wwnd * ztop / (ztop - topo_c)
    par_temp = 1 / (ztop - topo_c)**2.0D0
    par_sigmax = par_temp * (topo_e - topo_w) / 2.0D0 / dist_we
    par_sigmay = par_temp * (topo_n - topo_s) / 2.0D0 / dist_sn

    h_0 = (2.0D0 * sigma(2:vlevel - 1) - sigma(1:vlevel - 2) - sigma(3:vlevel)) / (&
  &   sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:vlevel&
  &   - 1))
    ! n represents negative
    h_n1 = (sigma(3:vlevel) - sigma(2:vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(2:&
  &   vlevel - 1)) / (sigma(3:vlevel) - sigma(1:vlevel - 2))
    ! p represents positive
    h_p1 = (sigma(1:vlevel - 2) - sigma(2:vlevel - 1)) / (sigma(3:vlevel) - sigma(2:&
  &   vlevel - 1)) / (sigma(1:vlevel - 2) - sigma(3:vlevel))
    par_ysigmad = 0.0_8
    par_ysigmad(2:vlevel - 1) = h_0 * y1d(2:vlevel - 1) + h_p1 * y1d(3:vlevel) + &
  &   h_n1 * y1d(1:vlevel - 2)
    par_ysigma(2:vlevel - 1) = y1(2:vlevel - 1) * h_0 + y1(3:vlevel) * h_p1 + y1(1&
  &   :vlevel - 2) * h_n1
    par_ysigmad(vlevel) = 0.0_8
    par_ysigma(vlevel) = 0.0D0

    IF (PRESENT(righthand)) THEN
      temp = (y_n(2:vlevel - 1) - y_s(2:vlevel - 1)) / (dist_sn * 2.0D0) - &
  &     par_sigmay * par_ysigma(2:vlevel - 1)
      temp0 = (y_e(2:vlevel - 1) - y_w(2:vlevel - 1)) / (dist_we * 2.0D0) - &
  &     par_sigmax * par_ysigma(2:vlevel - 1)
      tend(2:vlevel - 1) = righthandd(2:vlevel - 1) - temp * vwndd(2:vlevel - 1) -&
  &     vwnd(2:vlevel - 1) * ((y_nd(2:vlevel - 1) - y_sd(2:vlevel - 1)) / (dist_sn *&
  &     2.0D0) - par_sigmay * par_ysigmad(2:vlevel - 1)) - temp0 * uwndd(2:vlevel -&
  &     1) - uwnd(2:vlevel - 1) * ((y_ed(2:vlevel - 1) - y_wd(2:vlevel - 1)) / (&
  &     dist_we * 2.0D0) - par_sigmax * par_ysigmad(2:vlevel - 1)) - par_ysigma(2:&
  &     vlevel - 1) * wwnd_sd(2:vlevel - 1) - wwnd_s(2:vlevel - 1) * par_ysigmad(2:&
  &     vlevel - 1)
      ten(2:vlevel - 1) = righthand(2:vlevel - 1) - vwnd(2:vlevel - 1) * temp - &
  &     uwnd(2:vlevel - 1) * temp0 - wwnd_s(2:vlevel - 1) * par_ysigma(2:vlevel - 1)
      temp1 = vwnd(vlevel) / (dist_sn * 2.0D0)
      temp2 = uwnd(vlevel) / (dist_we * 2.0D0)
      tend(vlevel) = righthandd(vlevel) - temp1 * (y_nd(vlevel) - y_sd(vlevel)&
  &     ) - (y_n(vlevel) - y_s(vlevel)) * vwndd(vlevel) / (dist_sn * 2.0D0) - &
  &     temp2 * (y_ed(vlevel) - y_wd(vlevel)) - (y_e(vlevel) - y_w(vlevel)) *&
  &     uwndd(vlevel) / (dist_we * 2.0D0)
      ten(vlevel) = righthand(vlevel) - (y_n(vlevel) - y_s(vlevel)) * temp1 - &
  &     (y_e(vlevel) - y_w(vlevel)) * temp2
    ELSE
      temp0 = (y_e(2:vlevel - 1) - y_w(2:vlevel - 1)) / (dist_we * 2.0D0) - &
  &     par_sigmax * par_ysigma(2:vlevel - 1)
      temp = (y_n(2:vlevel - 1) - y_s(2:vlevel - 1)) / (dist_sn * 2.0D0) - &
  &     par_sigmay * par_ysigma(2:vlevel - 1)
      tend(2:vlevel - 1) = -(temp0 * uwndd(2:vlevel - 1)) - uwnd(2:vlevel - 1) * ((&
  &     y_ed(2:vlevel - 1) - y_wd(2:vlevel - 1)) / (dist_we * 2.0D0) - par_sigmax *&
  &     par_ysigmad(2:vlevel - 1)) - temp * vwndd(2:vlevel - 1) - vwnd(2:vlevel -&
  &     1) * ((y_nd(2:vlevel - 1) - y_sd(2:vlevel - 1)) / (dist_sn * 2.0D0) - par_sigmay&
  &     * par_ysigmad(2:vlevel - 1)) - par_ysigma(2:vlevel - 1) * wwnd_sd(2:&
  &     vlevel - 1) - wwnd_s(2:vlevel - 1) * par_ysigmad(2:vlevel - 1)
      ten(2:vlevel - 1) = -(uwnd(2:vlevel - 1) * temp0) - vwnd(2:vlevel - 1) * temp &
  &     - wwnd_s(2:vlevel - 1) * par_ysigma(2:vlevel - 1)
      temp2 = uwnd(vlevel) / (dist_we * 2.0D0)
      temp1 = vwnd(vlevel) / (dist_sn * 2.0D0)
      tend(vlevel) = -(temp2 * (y_ed(vlevel) - y_wd(vlevel))) - (y_e(vlevel) -&
  &     y_w(vlevel)) * uwndd(vlevel) / (dist_we * 2.0D0) - temp1 * (y_nd(vlevel) -&
  &     y_sd(vlevel)) - (y_n(vlevel) - y_s(vlevel)) * vwndd(vlevel) / (dist_sn *&
  &     2.0D0)
      ten(vlevel) = -((y_e(vlevel) - y_w(vlevel)) * temp2) - (y_n(vlevel) - y_s(&
  &     vlevel)) * temp1
    END IF
  END SUBROUTINE TENDENCY_D

  !  Differentiation of interp1d in forward (tangent) mode:
  !   variations   of useful results: xout
  !   with respect to varying inputs: xout xin
  SUBROUTINE INTERP1D_D(sigmain, xin, xind, xin_size, sigmaout, xout, &
  & xoutd, log_flag)
    IMPLICIT NONE
    INTEGER*4, INTENT(IN) :: xin_size
    INTEGER*4 :: i, j, xout_size
    CHARACTER(len=3), INTENT(IN), OPTIONAL :: log_flag
    REAL*8, INTENT(IN) :: sigmain(:), xin(:)
    REAL*8, INTENT(IN) :: xind(:)
    REAL*8, INTENT(IN) :: sigmaout(:)
    REAL*8, INTENT(OUT) :: xout(:)
    REAL*8, INTENT(OUT) :: xoutd(:)
    REAL*8 :: xint(xin_size)
    REAL*8 :: xintd(xin_size)
    INTRINSIC SIZE
    INTRINSIC PRESENT
    INTRINSIC DLOG
    INTRINSIC EXP
    xout_size = SIZE(sigmaout)

    IF (PRESENT(log_flag) .AND. log_flag .EQ. 'LOG') THEN
      xintd = xind / xin
      xint = DLOG(xin)
    ELSE
      xintd = xind
      xint = xin
    END IF
    DO 120 i = 1, xout_size
      DO j = 1, xin_size
        IF (sigmain(j) .EQ. sigmaout(i)) THEN
          GOTO 100
        ELSE IF (sigmain(j) .GT. sigmaout(i) .AND. j .LE. xin_size) THEN
          GOTO 110
        ELSE IF (sigmain(j) .LT. sigmaout(i) .AND. j .EQ. xin_size) THEN
          xoutd(i) = xintd(j - 1) + (sigmaout(i) - sigmain(j - 1)) * (xintd(j) -&
  &         xintd(j - 1)) / (sigmain(j) - sigmain(j - 1))
          xout(i) = xint(j - 1) + (xint(j) - xint(j - 1)) / (sigmain(j) - sigmain(j -&
  &         1)) * (sigmaout(i) - sigmain(j - 1))
        END IF
      END DO
      GOTO 120
100   xoutd(i) = xintd(j)
      xout(i) = xint(j)
      GOTO 120
110   IF (j .GT. 1) THEN
        xoutd(i) = xintd(j - 1) + (sigmaout(i) - sigmain(j - 1)) * (xintd(j) - xintd&
  &       (j - 1)) / (sigmain(j) - sigmain(j - 1))
        xout(i) = xint(j - 1) + (xint(j) - xint(j - 1)) / (sigmain(j) - sigmain(j - 1)&
  &       ) * (sigmaout(i) - sigmain(j - 1))
      ELSE
        xoutd(i) = xintd(1) + (sigmaout(i) - sigmain(1)) * (xintd(2) - xintd(1))&
  &       / (sigmain(2) - sigmain(1))
        xout(i) = xint(1) + (xint(2) - xint(1)) / (sigmain(2) - sigmain(1)) * (&
  &       sigmaout(i) - sigmain(1))
      END IF
120   CONTINUE
      IF (PRESENT(log_flag) .AND. log_flag .EQ. 'LOG') THEN
        xoutd = EXP(xout) * xoutd
        xout = EXP(xout)
      END IF
      END SUBROUTINE INTERP1D_D

      END MODULE RK4D_m
