MODULE mo_types

  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_SHORT, C_INT, C_LONG_LONG, C_FLOAT, C_DOUBLE

  IMPLICIT NONE

  INTEGER, PARAMETER :: i8 = SELECTED_INT_KIND(2)
  INTEGER, PARAMETER :: i16 = C_SHORT
  INTEGER, PARAMETER :: i32 = C_INT
  INTEGER, PARAMETER :: i64 = C_LONG_LONG
  INTEGER, PARAMETER :: f32 = C_FLOAT
  INTEGER, PARAMETER :: f64 = C_DOUBLE

END MODULE mo_types
